---
settings:
  name: SANtricity commands
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  pdf:
    zip-level: 1
    zip-filename: santricity-commands.zip
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: CLI文件SANtricity
    url: "/index.html"
  - title: 新增功能
    url: "/whats-new.html"
  - section: get-started
  - section: commands-category
  - section: commands-a-z
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: CLI總覽
      url: get-started/overview-format-commands.html
    - title: CLI命令結構
      url: get-started/structure-of-a-cli-command.html
  - title: E系列文件
    links:
    - title: E系列系統文件
      url: https://docs.netapp.com/us-en/e-series/index.html
    - title: SANtricity 系統管理員 11.8
      url: https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html
    - title: SANtricity Unified Manager 6.
      url: https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html
  - title: 工具支援
    links:
    - title: NetApp 互通性對照表
      url: http://mysupport.netapp.com/matrix/
    - title: NetApp知識庫
      url: https://kb.netapp.com/
    - title: "（需要登入）Active IQ"
      url: https://activeiq.netapp.com/?source=aiqnsspage
    - title: E系列/SANtricity下載（需要登入）
      url: https://mysupport.netapp.com/site/downloads#E
product-family:
  name: E-Series
  repo: e-series-family
