---
permalink: get-started/command-line-parameters.html 
sidebar: sidebar 
keywords: legacy, command line, parameters 
summary: 推出的《支援E2800與E5700控制器的支援嵌入式Web服務的支援功能、可透過安全的HTTPS傳輸協定、在命令列上互動。SANtricity這些控制器可以選用符號傳輸協定來進行命令列互動。 
---
= 舊版命令列參數
:allow-uri-read: 
:icons: font
:imagesdir: ./media/




== 11.53和舊版命令列參數

推出的《支援E2800與E5700控制器的支援嵌入式Web服務的支援功能、可透過安全的HTTPS傳輸協定、在命令列上互動。SANtricity這些控制器可以選用符號傳輸協定來進行命令列互動。SYMBOL傳輸協定是唯一支援E2700和E5600控制器的傳輸協定。為了保留現有的指令碼並將轉換時間減至最短、CLI選項和語法會盡可能保留。但是、E2800和E5700控制器在安全性、驗證、AutoSupport 可靠性和警示訊息等方面的功能有一些差異、使這些控制器的某些CLI語法變得過時。不過、在某些情況下、只有在使用新https傳輸協定時、E2800或E5700上的語法才會過時。

對於僅適用於「* https *」用戶端類型的新參數、其結果是也僅適用於E2800或E5700控制器。

[cols="2*"]
|===
| 參數 | 定義 


 a| 
-'用戶端類型'
 a| 
此引數會強制建立適當的指令碼引擎。使用此選用參數搭配下列其中一個值：

* 「*自動*」-系統會自動執行裝置探索、以偵測適當的指令碼引擎類型。
* 「* https *」-即會建立REST型指令碼引擎。
* 「*符號*」-建立符號型指令碼引擎。




 a| 
「-u」
 a| 
使用'_username_'變數追蹤此參數。使用者名稱僅適用於「* https *」用戶端類型。此引數不適用於'*symbol *用戶端類型、將會被無訊息忽略。

如果指定UserName引數、則會執行裝置探索來判斷正確的用戶端類型（「* https *」vs.*符號*）。



 a| 
「-P」
 a| 
此引數需要兩個引數之一：

* 「_password_file_」-包含用於驗證的密碼。
* （短破折號）-從「stin」讀取密碼。


請注意、無論使用的是「* https *」用戶端類型或「* symbol *」用戶端類型、新增此引數都適用於所有控制器。



 a| 
「-k」
 a| 
此選用引數可讓「* https *」用戶端以不安全模式運作。這表示不會驗證儲存陣列的憑證。依預設、如果省略、將會執行適當的驗證。此引數不適用於'*symbol *用戶端類型、將會被無訊息忽略。

|===


== 僅適用於E2700或E5600控制器的命令列參數

由於E2700和E5600控制器沒有內嵌警示管理功能、因此這些命令列參數是適用的。這些參數不適用於E2800或E5700控制器。

[cols="2*"]
|===
| 參數 | 定義 


 a| 
答
 a| 
新增簡單網路管理傳輸協定（SNMP）設陷目的地或電子郵件地址警示目的地。

* 當您新增SNMP設陷目的地時、SNMP社群會自動定義為設陷的社群名稱、而「*主機*」則是要傳送設陷的系統的IP位址或網域名稱伺服器（DNS）主機名稱。
* 當您新增警示目的地的電子郵件地址時、「*電子郵件地址*」是您要傳送警示訊息的電子郵件地址。


[NOTE]
====
對於E2800和E5700儲存陣列、此命令列選項已過時。使用RESTful API、SANtricity 《系統管理程式》或「Curl」命令。

====


 a| 
「-m」
 a| 
指定電子郵件警示通知的寄送來源電子郵件伺服器主機名稱或IP位址。

[NOTE]
====
對於E2800和E5700儲存陣列、此命令列選項已過時。使用RESTful API、SANtricity 《系統管理程式》或「Curl」命令。

====


 a| 
s（小寫）
 a| 
顯示組態檔中與「-d」參數搭配使用時的警示設定。

[NOTE]
====
對於E2800和E5700儲存陣列、此命令列選項已過時。使用RESTful API、SANtricity 《系統管理程式》或「Curl」命令。

====


 a| 
-`-x'（小寫）
 a| 
移除SNMP設陷目的地或電子郵件地址警示目的地。「_community」是陷阱的SNMP社群名稱、而「_host_」是要傳送陷阱的系統IP位址或DNS主機名稱。

[NOTE]
====
對於E2800和E5700儲存陣列、此命令列選項已過時。使用RESTful API、SANtricity 《系統管理程式》或「Curl」命令。

====
|===


== 適用於所有以符號用戶端類型執行之控制器的命令列參數

[cols="2*"]
|===
| 參數 | 定義 


 a| 
「-R」（大寫）
 a| 
定義密碼的使用者角色。這些角色可以是：

* "* admin*（系統管理*）"-使用者有權變更儲存陣列組態。
* "*監控*（*監控*）"-使用者有權檢視儲存陣列組態、但無法進行變更。


只有搭配「*–p*」參數使用時、「*-R*」參數才有效、此參數會指定您定義儲存陣列的密碼。

只有在儲存陣列上啟用雙密碼功能時、才需要「*- R*」參數。在下列情況下、「*- R*」參數是不必要的：

* 儲存陣列未啟用雙密碼功能。
* 僅設定一個管理員角色、且未針對儲存陣列設定監控角色。


|===


== 適用於所有控制器和所有用戶端類型的命令列參數

[cols="2*"]
|===
| 參數 | 定義 


 a| 
「主機名稱或IP位址」
 a| 
指定頻內託管儲存陣列或頻外託管儲存陣列的主機名稱或網際網路傳輸協定（IP）位址（`_xxx.xxx.xxx.xxx _）。

* 如果您是透過頻內儲存管理來使用主機來管理儲存陣列、則必須使用「-n」參數或「-w」參數（如果有多個儲存陣列連接到主機）。
* 如果您是透過每個控制器上的乙太網路連線、使用頻外儲存管理來管理儲存陣列、則必須指定控制器的「主機名稱」或「IP位址」。
* 如果您先前已在「企業管理」視窗中設定儲存陣列、可以使用「-n」參數、依使用者提供的名稱來指定儲存陣列。
* 如果您先前已在「企業管理」視窗中設定儲存陣列、則可以使用「-w」參數、依其「全球識別碼」（WWID）來指定儲存陣列。




 a| 
答
 a| 
將儲存陣列新增至組態檔。如果您不使用「-a」參數搭配「_host-name-or -ip-address_」、自動探索會掃描本機子網路中的儲存陣列。



 a| 
-c'
 a| 
表示您正在輸入一或多個指令碼命令、以便在指定的儲存陣列上執行。以分號（`；）結束每個命令。不能在同一命令行中放置多個"-c"參數。您可以在「-c」參數之後加入多個指令碼命令。



 a| 
「-d」
 a| 
顯示指令碼組態檔的內容。檔案內容格式如下：「_storage系統名稱host-name1 host-name2_」



 a| 
「-e」
 a| 
在不執行語法檢查的情況下執行命令。



 a| 
「-F」（大寫）
 a| 
指定所有警示都會從哪個電子郵件地址傳送。



 a| 
-`-f'（小寫）
 a| 
指定檔案名稱、其中包含您要在指定儲存陣列上執行的指令碼命令。在這兩個參數都是用來執行指令碼命令的情況下、「-f」參數類似於「-c」參數。"-c"參數會執行個別指令碼命令。「-f]參數會執行指令碼命令檔案。根據預設、在檔案中執行指令碼命令時所遇到的任何錯誤都會被忽略、而且檔案會繼續執行。若要覆寫此行為、請在指令碼檔案中使用「set工作階段errorAction=stop」命令。



 a| 
「-g」
 a| 
指定包含電子郵件寄件者聯絡資訊的Ascii檔案、這些資訊將會包含在所有電子郵件警示通知中。CLI假設Ascii檔案僅為文字、不含分隔符號或任何預期格式。如果存在「userdata.txt"檔案、請勿使用「-g」參數。



 a| 
「-h」
 a| 
指定執行儲存陣列所連接之SNMP代理程式的主機名稱。使用「-h（h））參數搭配下列參數：

* 答
* 「-x'」




 a| 
「-I」（大寫）
 a| 
指定要包含在電子郵件警示通知中的資訊類型。您可以選取下列值：

* 「僅事件」：電子郵件中只會包含事件資訊。
* 「設定檔」-電子郵件中包含事件和陣列設定檔資訊。


您可以使用「-q'」參數指定電子郵件傳送的頻率。



 a| 
「-i」（小寫）
 a| 
顯示已知儲存陣列的IP位址。使用「-I」參數搭配「-d」參數。檔案內容格式如下：「_storage系統名稱ip-address1 IPaddress2_」



 a| 
「-n'」
 a| 
指定要在其中執行指令碼命令的儲存陣列名稱。當您使用「主機名稱或IP位址」時、此名稱為選用名稱。如果您使用頻內方法來管理儲存陣列、則如果有多個儲存陣列以指定位址連接至主機、則必須使用「-n」參數。如果不使用「主機名稱或IP位址」、則需要儲存陣列名稱。在「Enterprise Management（企業管理）」視窗中設定使用的儲存陣列名稱（也就是名稱列在組態檔中）、不得是任何其他已設定儲存陣列的重複名稱。



 a| 
「-o'」
 a| 
指定執行指令碼命令所產生之所有輸出文字的檔案名稱。使用「-o'參數搭配下列參數：

* -c'
* 「-f'」


如果您未指定輸出檔案、輸出文字會移至標準輸出（stdout）。所有非指令碼命令的命令輸出都會傳送至stdout、無論是否設定此參數。



 a| 
「-p」
 a| 
定義您要在其中執行命令的儲存陣列密碼。在下列情況下、不需要密碼：

* 尚未在儲存陣列上設定密碼。
* 密碼是在您執行的指令碼檔案中指定。
* 您可以使用「-c'參數和下列命令來指定密碼：


[listing]
----
set session password=password
----


 a| 
「-P」
 a| 
此引數需要兩個引數之一：

* 「_password_file_」-包含用於驗證的密碼。
* ？？（破折號）-從"stitdin"讀取密碼。


請注意、無論使用的是「* https *」用戶端類型或「* symbol *」用戶端類型、新增此引數都適用於所有控制器。



 a| 
-q
 a| 
指定您要接收事件通知的頻率、以及事件通知中傳回的資訊類型。每個關鍵事件都會產生至少包含基本事件資訊的電子郵件警示通知。這些值對`-q'參數有效：

* 「Every Event」（所有事件）-每封電子郵件警示通知都會傳回資訊。
* 「2」——每兩小時傳回資訊不超過一次。
* 「4」——每4小時傳回資訊不超過一次。
* 「8」——每8小時傳回一次資訊。
* 「12」——每12小時傳回資訊不超過一次。
* 24小時——每24小時傳回資訊不超過一次。


使用「-I」參數、您可以在電子郵件警示通知中指定資訊類型。

* 如果將「-I」參數設為「eventOnly」、則「-q」參數的唯一有效值為「everyEvent」。
* 如果您將「-I」參數設定為「profile」值或「支撐組合」值、此資訊會包含在電子郵件中、且頻率由「-q」參數指定。




 a| 
「快速」
 a| 
減少執行單行作業所需的時間。單行操作的一個例子是"REcreate snapshot volume（重新創建Snapshot Volume）"命令。此參數可在命令執行期間不執行背景處理程序、藉此縮短時間。對於涉及多個單行作業的作業、請勿使用此參數。廣泛使用此命令可能會使控制器的命令超過控制器所能處理的命令數、進而導致作業失敗。此外、通常從背景程序收集的狀態更新和組態更新、CLI也無法使用。此參數會導致依賴背景資訊的作業失敗。



 a| 
「-S」（大寫）
 a| 
隱藏資訊訊息、說明執行指令碼命令時所顯示的命令進度。（隱藏資訊訊息也稱為無聲模式。） 此參數會隱藏下列訊息：

* 執行語法檢查
* 完成同步檢查
* 執行指令碼
* 完成記錄執行
* 「Mcli completed Successfully」（已成功完成Mcl




 a| 
`-useLegacyTransferPort`
 a| 
用於將傳輸連接埠設定為 `8443` 而非預設值 `443`。



 a| 
-`-v'
 a| 
顯示組態檔中已知裝置與「-d」參數搭配使用時的目前全域狀態。



 a| 
「-w'」
 a| 
指定儲存陣列的WWID。此參數是"-n"參數的替代參數。使用「-w]參數搭配「-d」參數、即可顯示已知儲存陣列的WWID。檔案內容格式如下：「_storage系統名稱world-id-ID ip-address1 ip-address2_」



 a| 
「-X」（大寫）
 a| 
從組態中刪除儲存陣列。



 a| 
」
 a| 
顯示有關CLI命令的使用資訊。

|===