---
permalink: get-started/learn-about-volume-group-migration.html 
sidebar: sidebar 
keywords: volume, group, migration, learn, data, access, export, import, component 
summary: Volume群組移轉可讓您匯出Volume群組、以便將Volume群組匯入不同的儲存陣列。您也可以匯出Volume群組、以便離線儲存資料。 
---
= 了解 SANtricity 軟體中的捲組遷移
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volume群組移轉可讓您匯出Volume群組、以便將Volume群組匯入不同的儲存陣列。您也可以匯出Volume群組、以便離線儲存資料。

[CAUTION]
====
如果磁碟區群組包含支援NVMe或FIPS的磁碟機、則必須從來源陣列記錄/儲存安全金鑰和密碼、以便在開始移轉至目標陣列之前解除鎖定磁碟機。如果不知道安全金鑰和密碼、而且/或不需要資料完整性、則可以執行安全性清除。E系列儲存系統不支援混合使用不同的加密安全磁碟機。如需如何使用安全金鑰解除磁碟機鎖定、清除FIPS磁碟機、以及解除鎖定或重設鎖定NVMe磁碟機的詳細資訊、請參閱SANtricity 《支援系統管理程式》的線上說明。

====
[NOTE]
====
*可能會遺失資料存取*：您必須先匯出磁碟區群組、才能移動磁碟區群組或匯入磁碟區群組。

====


== 匯出Volume群組

匯出Volume群組作業會準備磁碟區群組中的磁碟機以供移除。您可以移除磁碟機以進行離線儲存、也可以將磁碟區群組匯入不同的儲存陣列。完成匯出Volume群組作業之後、所有磁碟機都會離線。儲存管理軟體不再顯示任何相關的磁碟區或可用容量節點。



== 不可匯出的元件

您必須先移除任何不可匯出的元件、才能完成匯出Volume群組程序。您必須移除下列元件：

* 持續保留
* 對應
* Volume複製配對
* 遠端鏡射配對
* 鏡射儲存庫




== Volume群組的基本匯出步驟

匯出Volume群組時、會在_SOURER_儲存陣列上包含這些步驟。

. 儲存儲存陣列組態。
. 停止所有I/O
. 備份Volume群組中磁碟區上的資料。
. 卸載或中斷磁碟區群組中磁碟區上的檔案系統。
. 找出磁碟區群組、並以來源與目的地儲存陣列名稱、磁碟區群組名稱及磁碟區群組中的磁碟機總數來標示磁碟機。
. 將Volume群組離線。
. 若要在磁碟匣內維持適當的通風、請取得空白磁碟機容器或新磁碟機、以便在移除與您匯出的磁碟區群組相關的磁碟機之後、可以更換磁碟機。


匯出Volume群組包括目標儲存陣列上的這些步驟。

. 確定目標儲存陣列有可用的磁碟機插槽。
. 確定目標儲存陣列支援您要匯入的磁碟機。
. 確定目標儲存陣列可支援新的磁碟區。
. 確定控制器上已安裝最新版本的韌體。
. 如果您要匯出RAID層級6 Volume群組、請確定目標儲存陣列支援RAID層級6。
. 請確定目標儲存陣列上已安裝最新版本的儲存管理軟體。
. 如果您要匯出已啟用磁碟機安全性的磁碟區群組、請確定已在目標儲存陣列上啟用磁碟機安全性。




== 匯入Volume群組

匯入Volume群組作業會將匯入的Volume群組新增至目標儲存陣列。完成匯入磁碟區群組作業之後、所有磁碟機都會處於最佳狀態。現在、任何相關的Volume或可用容量節點都會出現在安裝在目標儲存陣列上的儲存管理軟體中。



== Volume群組的基本匯入步驟

[NOTE]
====
您必須先將Volume群組中的所有磁碟機插入磁碟匣、然後才能匯入Volume群組。

====
匯入Volume群組包括目標儲存陣列上的下列步驟：

. 將匯出的磁碟機插入可用的磁碟機插槽。
. 請檢閱匯入報告、以取得您要匯入之Volume群組的總覽。
. 檢查不可壓入的元件。
. 確認您要繼續進行匯入程序。




== 不可攜帶的元件

部分元件無法在匯入Volume群組程序期間匯入。這些元件會在程序期間移除：

* 持續保留
* 對應
* Volume複製配對
* 遠端鏡射配對
* 鏡射儲存庫

