---
permalink: commands-a-z/autoconfigure-storagearray.html 
sidebar: sidebar 
keywords: autoconfigure storage array,supported, roles, syntax, parameters, minimum firmware level 
summary: autoConfigure storageArray命令會自動設定儲存陣列。 
---
= 自動設定儲存陣列
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「autoConfigure storageArray」命令會自動設定儲存陣列。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

在輸入「autocConfigure storageArray」命令之前、請先執行「show storageArray autosconfiguration」命令。「show storageArray autoconfiguration」命令會以有效磁碟機類型、RAID層級、磁碟區資訊和熱備援資訊清單的形式傳回組態資訊。（此清單對應於「AutoConfigure storageArray」命令的參數。） 控制器會稽核儲存陣列、然後判斷儲存陣列可支援的最高RAID層級、以及RAID層級最有效率的磁碟區定義。如果傳回清單中所述的組態可接受、您可以輸入「AutoConfigure storageArray」命令、但不需輸入任何參數。如果您想要修改組態、可以變更參數以符合組態需求。您可以變更單一參數或所有參數。輸入「AutoConfigure storageArray」命令後、控制器會使用預設參數或您選取的參數來設定儲存陣列。



== 語法

[source, cli, subs="+macros"]
----
autoConfigure storageArray
[driveType=(SAS | NVMe4K)]
[driveMediaType=(hdd | ssd | allMedia | unknown)]
[raidLevel=(0 | 1 | 3 | 5 | 6)]
pass:quotes[[volumeGroupWidth=_numberOfDrives_]]
pass:quotes[[volumeGroupCount=_numberOfVolumeGroups_]]
pass:quotes[[volumesPerGroupCount=_numberOfVolumesPerGroup_]]
pass:quotes[[hotSpareCount=_numberOfHotSpares_]]
pass:quotes[[segmentSize=_segmentSizeValue_]]
[cacheReadPrefetch=(TRUE | FALSE)]
pass:quotes[[readAheadMultiplier=_multiplierValue_]]
[securityType=(none | capable | enabled)]
[secureDrives=(fips | fde)]
[dataAssurance=(none | enabled)]
[blockSize=(512 | 4096)]
----


== 參數

|===
| 參數 | 說明 


 a| 
「DiveType」
 a| 
您要用於儲存陣列的磁碟機類型。

當儲存陣列中有多種磁碟機時、您必須使用此參數。

這些磁碟機類型有效：

* 「as」
* 《NVMe4K》




 a| 
「DiveMediaType」
 a| 
您要用於儲存陣列的磁碟機媒體類型。

當儲存陣列中有多種磁碟機媒體類型時、您必須使用此參數。

這些磁碟機媒體類型有效：

* HDD（HDD）-如果您有硬碟機、請使用此選項。
* 「SD」-當您有固態磁碟時、請使用此選項。
* "unknown"（未知）-如果您不確定磁碟機匣中有哪些類型的磁碟機媒體、請使用




 a| 
《raidLevel》
 a| 
儲存陣列中包含磁碟機的磁碟區群組RAID層級。有效的RAID層級為「0」、「1」、「3」、「5」或「6」。



 a| 
「Volume Group寬度」
 a| 
儲存陣列磁碟區群組中的磁碟機數量。



 a| 
「volumeGroupCount」
 a| 
儲存陣列中的Volume群組數目。使用整數值。



 a| 
"volumesPerGroupCount"
 a| 
每個Volume群組容量相等的Volume數量。使用整數值。



 a| 
《熱點計數》
 a| 
儲存陣列中所需的熱備援磁碟機數目。使用整數值。



 a| 
'大小'
 a| 
控制器在磁碟區中的單一磁碟機上寫入資料的資料量（以KB為單位）、然後再將資料寫入下一個磁碟機。有效值為「4（僅SSD）」、「8」、「16」、「32」、「64」、「128」、 "256"或"512"。



 a| 
「cacheReadPrefetch」
 a| 
開啟或關閉快取讀取預先擷取的設定。若要關閉快取讀取預先擷取、請將此參數設為「假」。若要開啟快取讀取預先擷取、請將此參數設為「true」。



 a| 
《紅人倍數》
 a| 
此參數定義讀入快取的額外資料區塊數量。有效值範圍從「0」到「65535"。

[NOTE]
====
此參數已過時、將在未來的儲存管理軟體版本中移除。若要獲得最佳操作、請使用「cacheReadPrefetch」參數。

====


 a| 
「生態類型」
 a| 
此設定可在建立磁碟區群組及所有相關磁碟區時、指定安全性層級。這些設定有效：

* 「無」-磁碟區群組和磁碟區不安全。
* 「Capable」（功能）：磁碟區群組和磁碟區可以設定安全性、但尚未啟用安全性。
* 「已啟用」-磁碟區群組和磁碟區已啟用安全功能。




 a| 
"RecureDrives"
 a| 
磁碟區群組中要使用的安全磁碟機類型。這些設定有效：

* 「FIPS」-僅使用FIPS相容磁碟機。
* 「FDE」-使用FDE相容磁碟機。


[NOTE]
====
請搭配使用此參數與「安全性類型」參數。如果您為「安全性類型」參數指定「無」、則會忽略「RecureDrives」參數的值、因為不安全的磁碟區群組不需要指定安全磁碟機類型。

====


 a| 
「區塊大小」
 a| 
已建立磁碟區的區塊大小（以位元組為單位）。支援的值為 `512` 和 `4096`。

|===


== 磁碟機與磁碟區群組

Volume群組是一組磁碟機、由儲存陣列中的控制器邏輯分組。磁碟區群組中的磁碟機數量是RAID層級和控制器韌體的限制。建立Volume群組時、請遵循下列準則：

* 從韌體版本7.10開始、您可以建立一個空的Volume群組、以便保留容量供日後使用。
* 您無法在單一磁碟區群組中混用磁碟機類型。
* 您無法在單一磁碟區群組中混用HDD和SSD磁碟機。
* Volume群組中的磁碟機數量上限取決於下列條件：
+
** 控制器類型
** RAID層級


* RAID層級包括：0、1、3、5和6。
+
** 具有RAID層級3、RAID層級5或RAID層級6的Volume群組不能有超過30個磁碟機、而且至少必須有三個磁碟機。
** RAID層級6的Volume群組必須至少有五個磁碟機。
** 如果RAID層級1的Volume群組有四個以上的磁碟機、儲存管理軟體會自動將Volume群組轉換成RAID層級10、亦即RAID層級1 + RAID層級0。


* 若要啟用紙匣/藥櫃遺失保護、請參閱下表以瞭解其他條件：


|===
| 層級 | 紙匣遺失保護的準則 | 所需的最小紙匣數量 


 a| 
磁碟集區
 a| 
單一磁碟匣中的磁碟集區不含兩個以上的磁碟機
 a| 
6.



 a| 
RAID 6
 a| 
磁碟區群組在單一磁碟匣中不含兩個以上的磁碟機
 a| 
3.



 a| 
RAID 3或RAID 5
 a| 
磁碟區群組中的每個磁碟機都位於獨立的磁碟匣中
 a| 
3.



 a| 
RAID 1
 a| 
RAID 1配對中的每個磁碟機都必須位於獨立的磁碟匣中
 a| 
2.



 a| 
RAID 0
 a| 
無法達到紙匣遺失保護。
 a| 
不適用

|===
|===
| 層級 | 藥櫃損失保護條件 | 所需的藥櫃數量下限 


 a| 
磁碟集區
 a| 
此集區包含來自所有五個抽取器的磁碟機、每個抽取器中的磁碟機數量相同。如果磁碟集區包含15、20、25、30、35、 40、45、50、55或60個磁碟機。
 a| 
5.



 a| 
RAID 6
 a| 
磁碟區群組在單一藥櫃中不包含兩個以上的磁碟機。
 a| 
3.



 a| 
RAID 3或RAID 5
 a| 
磁碟區群組中的每個磁碟機都位於獨立的磁碟櫃中。
 a| 
3.



 a| 
RAID 1
 a| 
鏡射配對中的每個磁碟機都必須位於獨立的抽屜中。
 a| 
2.



 a| 
RAID 0
 a| 
無法達到藥櫃損失保護。
 a| 
不適用

|===


== 熱備援

利用Volume群組、保護資料的重要策略是將儲存陣列中的可用磁碟機指派為熱備援磁碟機。熱備援磁碟機不含資料、可在RAID 1、RAID 3、RAID 5或RAID 6 Volume群組中、作為儲存陣列的待命磁碟機。熱備援可為儲存陣列增加另一層備援。

一般而言、熱備援磁碟機的容量必須等於或大於其所保護磁碟機的已用容量。熱備援磁碟機必須具有相同的媒體類型、相同的介面類型、以及與其保護磁碟機相同的容量。

如果儲存陣列中的磁碟機故障、則熱備援磁碟機通常會自動取代故障磁碟機、而不需要您的介入。如果某個熱備援磁碟機故障時可用、則控制器會使用備援資料同位元檢查、將資料重建到熱備援磁碟機上。資料清空支援也可在軟體將磁碟機標示為「故障」之前、將資料複製到熱備援磁碟機。

實體更換故障磁碟機之後、您可以使用下列任一選項來還原資料：

當您更換故障磁碟機時、熱備援磁碟機的資料會複製回更換磁碟機。此動作稱為「反向複製」。

如果您將熱備援磁碟指定為磁碟區群組的永久成員、則不需要複製作業。

磁碟區群組的磁碟匣遺失保護和藥櫃遺失保護的可用度取決於磁碟區群組所在磁碟機的位置。由於磁碟機故障和熱備援磁碟機的位置、因此可能會遺失磁碟匣遺失保護和藥櫃遺失保護。為了確保紙匣遺失保護和藥櫃遺失保護不受影響、您必須更換故障的磁碟機、以啟動回寫程序。

儲存陣列會自動選取支援Data Assurance（DA）的磁碟機、以進行啟用DA的磁碟區的熱備援涵蓋範圍。

請確定儲存陣列中有支援DA的磁碟機、以提供啟用DA的磁碟區的熱備援涵蓋範圍。如需具備DA功能磁碟機的詳細資訊、請參閱資料保證功能。

安全功能（FIPS和FDE）磁碟機可作為熱備援、用於具有安全功能和不安全功能的磁碟機。不安全的磁碟機可為其他不安全的磁碟機提供涵蓋範圍、如果磁碟區群組未啟用安全功能、則可為具有安全功能的磁碟機提供涵蓋範圍。FIPS Volume群組只能使用FIPS磁碟機作為熱備援磁碟機；不過、您可以使用FIPS熱備援磁碟機作為不安全、安全且安全的磁碟區群組。

如果您沒有熱備援磁碟機、您仍可在儲存陣列運作時更換故障磁碟機。如果磁碟機是RAID 1、RAID 3、RAID 5或RAID 6 Volume群組的一部分、則控制器會使用備援資料同位元檢查、自動將資料重新建置到替換磁碟機上。此行動稱為「重建」。



== 區段大小

區段大小決定控制器在磁碟區中的單一磁碟機上寫入多少資料區塊、然後再將資料寫入下一個磁碟機。每個資料區塊儲存512個位元組的資料。資料區塊是最小的儲存單位。區段的大小決定其包含多少資料區塊。例如、8-KB區段可容納16個資料區塊。64 KB區段可容納128個資料區塊。

當您輸入區段大小的值時、會對照控制器在執行時間提供的支援值來檢查該值。如果您輸入的值無效、控制器會傳回有效值清單。使用單一磁碟機進行單一要求時、其他磁碟機仍可同時處理其他要求。如果磁碟區位於單一使用者正在傳輸大量資料（例如多媒體）的環境中、則當單一資料傳輸要求以單一資料等量磁碟區來處理時、效能就會達到最大化。（資料等量磁碟區是區段大小乘以磁碟區群組中用於資料傳輸的磁碟機數量。） 在此情況下、多個磁碟機用於相同的要求、但每個磁碟機只能存取一次。

若要在多使用者資料庫或檔案系統儲存環境中達到最佳效能、請設定區段大小、將滿足資料傳輸要求所需的磁碟機數量降至最低。



== 快取讀取預先擷取

快取讀取預先擷取可讓控制器在控制器讀取及複製主機從磁碟機要求的資料區塊時、將其他資料區塊複製到快取中。此動作可增加日後從快取執行資料要求的機會。對於使用循序資料傳輸的多媒體應用程式而言、快取讀取預先擷取非常重要。「cacheReadPrefetch」參數的有效值為「true」或「假」。預設值為「true」。



== 安全類型

使用「安全性類型」參數來指定儲存陣列的安全性設定。

您必須先建立儲存陣列安全性金鑰、才能將「安全性類型」參數設定為「已啟用」。使用「create storageArray SECURITY Key」命令建立儲存陣列安全金鑰。這些命令與安全金鑰有關：

* 「create storageArray securityKey」
* 「匯出storageArray安全金鑰」
* 「Import storageArray securityKey」
* 「et storageArray安全性金鑰」
* 「啟用volumeGroup [volumeGroupName]安全性」
* 「啟用diskPool [diskPoolName] Security」




== 安全磁碟機

安全的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。使用「RecureDrives」參數指定要使用的安全磁碟機類型。您可以使用的值是「FIPS」和「FDE」。



== 命令範例

[listing]
----
autoConfigure storageArray securityType=capable secureDrives=fips;
----


== 最低韌體層級

7.10新增RAID層級6功能、並移除熱備援限制。

7.50新增「最安全類型」參數。

7.75新增了「data Assurance」參數。

8.25新增「RecureDrives」參數。
