---
permalink: commands-a-z/check-storagearray-connectivity.html 
sidebar: sidebar 
keywords: check, storage array, connectivity 
summary: Check storageArray Connectivity命令可驗證本機儲存陣列和遠端儲存陣列是否有通訊路徑、並顯示本機與遠端儲存陣列之間的連線詳細資料。 
---
= 檢查儲存陣列連線能力
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Check storageArray connection效 命令用於驗證本地儲存陣列和遠端儲存陣列是否具有通訊路徑、並顯示本機與遠端儲存陣列之間的連線詳細資料。



== 支援的陣列

此命令適用於任何個別儲存陣列、但有一些限制。如果您在E2700或E5600陣列上執行命令、則沒有任何限制。

[NOTE]
====
E4000 ， E2800 ， E5700 ， EF600 和 EF300 平台不支援此命令。

====


== 角色

不適用



== 背景

在建立非同步鏡射群組之前、您應該先檢查本機儲存陣列和遠端儲存陣列是否可以彼此通訊。執行此命令時、系統會查詢所有合格主機連接埠上的遠端儲存陣列、以判斷哪些連接埠連接至遠端儲存陣列。測試結果為本機儲存陣列上所有連接埠的清單、以及可透過該連接埠存取的遠端儲存陣列連接埠位址清單。

[NOTE]
====
連線能力是使用所有可能的通道進行測試、如果是雙控制器組態、則會從每個控制器檢查連線能力。檢查兩個儲存陣列之間的連線可能需要20分鐘的時間。

====


== 語法

[source, cli, subs="+macros"]
----
check storageArray connectivity
(remoteStorageArrayName=pass:quotes[_"storageArrayName"_]|
remoteStorageArrayWwid=<pass:quotes[_wwID_]>)
----


== 參數

|===
| 參數 | 說明 


 a| 
"REmoteStorageArrayName"
 a| 
您要檢查連線的遠端儲存陣列名稱。將儲存陣列名稱括在雙引號（""）內。



 a| 
"REmoteStorageArrayWwide"
 a| 
您要檢查連線的儲存陣列的全球識別碼（WWID）。您可以使用WWID而非儲存陣列名稱來識別儲存陣列。將WWID括在尖括弧內（<>）。

|===


== 附註

在兩個儲存陣列之間建立鏡像之前、必須先透過光纖通道連線或iSCSI連線來連線。

光纖通道非同步鏡射必須在兩個儲存陣列上啟動、才能彼此通訊以進行鏡射或連線檢查。

如果本機儲存陣列支援iSCSI、則會檢查透過iSCSI的連線能力。如果本機儲存陣列支援Fibre Channel、且光纖通道鏡射已啟動、則會檢查透過Fibre Channel的連線能力。如果本機儲存陣列不支援iSCSI或Fibre Channel、則會顯示錯誤訊息並中止作業。



== 最低韌體層級

7.84
