---
permalink: commands-a-z/check-volume-parity.html 
sidebar: sidebar 
keywords: check, volume, parity 
summary: Check Volume同位元檢查命令會檢查磁碟區是否有同位元檢查和媒體錯誤、然後將檢查結果寫入檔案。 
---
= 檢查磁碟區同位元檢查
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Check Volume同位元檢查命令會檢查磁碟區是否有同位元檢查和媒體錯誤、然後將檢查結果寫入檔案。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 語法

[source, cli, subs="+macros"]
----
check volume pass:quotes[[_volumeName_]] parity
[parityErrorFile=pass:quotes[_filename_]]
[mediaErrorFile=pass:quotes[_filename_]]
[priority=(highest | high | medium | low | lowest)]
[startingLBA=pass:quotes[_LBAvalue_]]
[endingLBA=pass:quotes[_LBAvalue_]]
[verbose=(TRUE | FALSE)]
----


== 參數

|===
| 參數 | 說明 


 a| 
《Volume》（Volume）
 a| 
您要檢查同位元檢查的特定Volume名稱。將磁碟區名稱括在方括弧（[]）內。如果Volume名稱包含特殊字元或僅包含數字、則必須在方括弧內以雙引號（""）括住識別碼。



 a| 
「parityErrorFile」
 a| 
您要儲存同位元檢查錯誤資訊的檔案路徑和檔案名稱。將檔案名稱括在雙引號（""）內。例如：

「file="C:\Program Files\CLI/logs\parerr.txt"」

此命令不會自動將副檔名附加至儲存的檔案。輸入檔案名稱時、您必須指定副檔名。



 a| 
「新知檔案」
 a| 
您要儲存媒體錯誤資訊的檔案路徑和檔案名稱。將檔案名稱括在雙引號（""）內。例如：

「file="C:\Program Files\CLI/logs\meterr.txt"」

此命令不會自動將副檔名附加至儲存的檔案。輸入檔案名稱時、您必須指定副檔名。



 a| 
" 優先 "
 a| 
同位元檢查相對於主機I/O活動的優先順序。有效值包括「最高」、「高」、「中等」、「低」或「最低」。最低優先率有利於系統效能、但同位元檢查需要較長時間。最高的優先順序率有利於同位元檢查、但系統效能可能會受損。



 a| 
《tartingLBA》
 a| 
起始邏輯區塊位址。



 a| 
《endingLBA》（endingLBA）
 a| 
結束邏輯區塊位址。



 a| 
「詳細」
 a| 
此設定可擷取進度詳細資料、例如完成百分比、並在掃描Volume同位元時顯示資訊。若要擷取進度詳細資料、請將此參數設為「true」。若要避免擷取進度詳細資料、請將此參數設為「假」。

|===


== 附註

起始邏輯區塊位址和結束邏輯區塊位址對於非常大型的單一Volume LUN或命名空間非常有用。在非常大型的單一Volume LUN或命名空間上執行Volume同位元檢查可能需要很長時間。藉由定義資料區塊的起始位址和結束位址、您可以縮短磁碟區同位元檢查完成所需的時間。



== 最低韌體層級

11.80 - 此命令已過時。
