---
permalink: commands-a-z/create-diskpool.html 
sidebar: sidebar 
keywords: create, disk pool 
summary: create diskPool命令會根據指定的參數建立新的磁碟集區。 
---
= 建立磁碟集區
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「create diskPool」命令會根據指定的參數建立新的磁碟集區。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800、E5700、 EF600和EF300陣列、只要安裝所有SMcli套件即可。



== 角色

若要在E2800、E5700、EF600或EF300儲存陣列上執行此命令、您必須具有儲存管理員角色。



== 背景

您可以輸入磁碟機清單或磁碟集區要使用的磁碟機類型、來建立磁碟集區。

[NOTE]
====
如果您輸入磁碟機清單、請確定所有磁碟機的容量都相同。如果磁碟機的容量不相同、則磁碟集區中的每個磁碟機都會報告容量等於最小的磁碟機。

====


== 語法

[listing, subs="+macros"]
----
create diskPool
(drives=pass:quotes[_(trayID1_],pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDN_],pass:quotes[[_drawerIDN,_]]pass:quotes[_slotIDN)_]|
driveType=(fibre | SATA | SAS | NVMe4K))
 userLabel=pass:quotes[_"diskPoolName"_]
[driveCount=pass:quotes[_driveCountValue_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[warningThreshold=(pass:quotes[_warningThresholdValue_] | default)]
[criticalThreshold=(pass:quotes[_criticalThresholdValue_] | default)]
[criticalPriority=(highest|high|medium|low|lowest)]
[backgroundPriority=(highest|high|medium|low|lowest)]
[degradedPriority=(highest|high|medium|low|lowest)]
[securityType=(none | capable | enabled )]
[secureDrives=(fips | fde )]
[driveMediaType=(hdd | ssd | allMedia | unknown)]
[dataAssurance=(none|enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== 參數

|===
| 參數 | 說明 


 a| 
《發展》
 a| 
您要指派給您要建立之磁碟集區的磁碟機。對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800、E5700、EF600和EF300控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。



 a| 
「userLabel」
 a| 
您要為新磁碟集區指定的名稱。將磁碟集區名稱括在雙引號（""）內。



 a| 
"DiveCount"
 a| 
"driveCount"參數會將磁碟集區候選項目限制為指定的編號。使用此參數時、HDD磁碟機可輸入的最小值為11。SSD磁碟機的最小值為8。

[NOTE]
====
「磁碟數」少於11的SSD資源池僅限於RAID 1磁碟區。

====


 a| 
「warningThreshold」
 a| 
當磁碟集區即將滿時、您會收到警示的儲存容量百分比。使用整數值。例如、值60表示60%。為達到最佳操作效果、此參數的值必須小於「criticalThreshold」參數的值。

有效值介於0到100之間。

預設值為50。

將此參數設為0（零）會停用警告警示。

如果您將此值設為「預設」、則警告警示臨界值由控制器韌體決定。



 a| 
「嚴重臨界值」
 a| 
當磁碟集區即將滿時、您會收到嚴重警示的儲存容量百分比。使用整數值。例如、值70表示70%。為達到最佳作業效果、此參數的值必須大於「warningThreshold」參數的值。

有效值介於0到100之間。

預設值為85%。

將此參數設為0（零）會停用警告警示和重大警示。

如果您將此值設為「預設」、則關鍵警示臨界值由控制器韌體決定。



 a| 
「重要優先」
 a| 
磁碟集區中重要事件的重建作業優先順序。例如、磁碟集區在至少兩個磁碟機故障後重建。

有效值包括「最高」、「高」、「中等」、「低」及「最低」。預設值為「最高」。



 a| 
「背景優先順序」
 a| 
磁碟集區上的背景作業優先順序。

有效值包括「最高」、「高」、「中等」、「低」及「最低」。預設值為「低」。



 a| 
「Dedgraded匯款」
 a| 
磁碟集區上降級活動的優先順序。例如、磁碟集區在一個磁碟機故障後重建。

有效值包括「最高」、「高」、「中等」、「低」及「最低」。預設值為「高」。



 a| 
「生態類型」
 a| 
用於指定建立磁碟集區時的安全性層級的設定。磁碟集區的所有候選磁碟區都將具有指定的安全性類型。

這些設定有效：

* 「無」- Volume候選者不安全。
* 「Capable」（功能）：磁碟區候選者可以設定安全性、但尚未啟用安全性。
* 「已啟用」：磁碟區候選者已啟用安全功能。


預設值為「無」。



 a| 
"RecureDrives"
 a| 
磁碟區群組中要使用的安全磁碟機類型。這些設定有效：

* 「FIPS」-僅使用FIPS相容磁碟機。
* 「FDE」-使用FDE相容磁碟機。


[NOTE]
====
請搭配使用此參數與「安全性類型」參數。如果您為「安全性類型」參數指定「無」、則會忽略「RecureDrives」參數的值、因為不安全的磁碟集區不需要指定安全磁碟機類型。

====
[NOTE]
====
除非您同時使用「driveCounts」參數、否則會忽略此參數。如果您指定要用於磁碟集區的磁碟機、而非提供計數、請根據所需的安全性類型、在選擇清單中指定適當的磁碟機類型。

====


 a| 
「DiveMediaType」
 a| 
要用於磁碟集區的磁碟機媒體類型。

當儲存陣列中有多種磁碟機媒體類型時、您必須使用此參數。

這些磁碟機媒體有效：

* HDD（HDD）-如果您有硬碟機、請使用此選項。
* 「SD」-當您有固態磁碟時、請使用此選項。
* "unknown"（未知）-如果您不確定磁碟機匣中有哪些類型的磁碟機媒體、請使用此選項
* "ALLMEDIA"（ALLMEDIA）-如果您想要使用磁碟機匣中的所有磁碟機媒體類型、請使用此選項


預設值為「HDD」。

[NOTE]
====
控制器韌體不會在同一個磁碟集區中混用「HDD」和「SD」磁碟機媒體、無論您選擇的設定為何。

====


 a| 
"REsourceProvisioningCapable（資源配置資源可）"
 a| 
指定是否啟用資源資源配置功能的設定。若要停用資源資源配置、請將此參數設為「假」。預設值為「true」。

|===


== 附註

每個磁碟集區名稱都必須是唯一的。您可以使用任何字母數字字元、底線（_）、連字號（-）和井號（#）的組合作為使用者標籤。使用者標籤最多可有30個字元。

如果您指定的參數無法滿足任何可用的候選磁碟機、則命令會失敗。通常、所有符合服務品質屬性的磁碟機都會以最佳候選磁碟機的形式傳回。但是、如果您指定磁碟機清單、某些傳回為候選磁碟機的可用磁碟機可能與服務品質屬性不符。

如果您未指定選用參數的值、則會指派預設值。



== 磁碟機

當您使用「driveType」參數時、該磁碟類型的所有未指派磁碟機都會用來建立磁碟集區。如果您想要限制磁碟集區中「driveType」參數所找到的磁碟機數量、可以使用「driveCount」參數來指定磁碟機數量。您只能在使用「driveType」參數時使用「driveCount」參數。

「磁碟機」參數可同時支援大容量磁碟機匣和低容量磁碟機匣。大容量磁碟機匣具有可容納磁碟機的抽屜。從磁碟機匣中滑出抽取器、以便存取磁碟機。低容量磁碟機匣沒有抽屜。對於大容量磁碟機匣、您必須指定磁碟機匣的識別碼（ID）、匣的識別碼、以及磁碟機所在插槽的識別碼。對於低容量磁碟機匣、您只需要指定磁碟機匣的ID、以及磁碟機所在插槽的ID。對於低容量磁碟機匣、識別磁碟機位置的另一種方法是指定磁碟機匣的ID、將抽取匣的ID設為「0」、然後指定磁碟機所在插槽的ID。

如果您輸入大容量磁碟機匣的規格、但磁碟機匣無法使用、儲存管理軟體會傳回錯誤訊息。



== 磁碟集區警示臨界值

每個磁碟集區都有兩個逐漸嚴重的警示層級、可在磁碟集區的儲存容量即將滿時通知使用者。警示的臨界值是磁碟集區中可用容量總計的已用容量百分比。警示如下：

* 警告：這是第一級警示。此層級表示磁碟集區中的已用容量即將滿。當達到警告警示的臨界值時、系統會產生需要注意的條件、並將事件張貼至儲存管理軟體。嚴重臨界值會取代警告臨界值。預設的警告臨界值為50%。
* 嚴重：這是最嚴重的警示等級。此層級表示磁碟集區中的已用容量即將滿。當達到臨界警示的臨界值時、系統會產生需要注意的條件、並將事件張貼至儲存管理軟體。嚴重臨界值會取代警告臨界值。嚴重警示的預設臨界值為85%。


若要生效、警告警示的值一律必須小於嚴重警示的值。如果警告警示的值與嚴重警示的值相同、則只會傳送嚴重警示。



== 磁碟集區背景作業

磁碟集區支援下列背景作業：

* 重建
* 即時可用度格式（IAF）
* 格式
* 動態容量擴充（DCE-）
* 動態Volume Expansion（DVE）（對於磁碟資源池、DVE實際上不是背景作業、但DVE支援同步作業。）


磁碟集區不會將背景命令排入佇列。您可以依序啟動數個背景命令、但一次啟動多個背景作業會延遲完成先前啟動的命令。支援的背景作業具有下列相對優先順序層級：

. 重建
. 格式
. 廢時
. DCE-




== 安全類型

使用「安全性類型」參數來指定儲存陣列的安全性設定。

您必須先建立儲存陣列安全性金鑰、才能將「安全性類型」參數設定為「已啟用」。使用「create storageArray SECURITY Key」命令建立儲存陣列安全金鑰。這些命令與安全金鑰有關：

* 「create storageArray securityKey」
* 「匯出storageArray安全金鑰」
* 「Import storageArray securityKey」
* 「et storageArray安全性金鑰」
* 「啟用volumeGroup [volumeGroupName]安全性」
* 「啟用diskPool [diskPoolName] Security」




== 安全磁碟機

安全的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。使用「RecureDrives」參數指定要使用的安全磁碟機類型。您可以使用的值是「FIPS」和「FDE」。



== 命令範例

[listing]
----
create diskPool driveType=SAS userLabel="FIPS_Pool" driveCount=11 securityType=capable secureDrives=fips;
----


== 最低韌體層級

7.83

8.20新增下列參數：

* 「TrayLossProtect」
* 《DrawerLosProtect》


8.25新增「RecureDrives」參數。

8.63新增了「資源配置資源Capable」參數。

11.73更新了"driveCount"參數。
