---
permalink: commands-a-z/create-volumegroup.html 
sidebar: sidebar 
keywords: create, volume, group 
summary: 當您輸入一組未指派的磁碟機時、create volumeGroup命令會建立可用容量磁碟區群組、或是一個具有一個磁碟區的磁碟區群組。 
---
= 建立卷宗組 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您輸入一組未指派的磁碟機時、「create volumeGroup」命令會建立可用容量磁碟區群組、或建立一個具有一個磁碟區的磁碟區群組。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 語法

[source, cli, subs="+macros"]
----
create volumeGroup
drives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]pass:quotes[_slotIDn)_]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeGroupName"_]
[driveMediaType=(HDD | SSD | unknown | allMedia)]
[driveType=(SAS | NVMe4K)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== 參數

|===
| 參數 | 說明 


 a| 
《發展》
 a| 
您要指派給您要建立之磁碟區群組的磁碟機。對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800和E5700控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。



 a| 
《raidLevel》
 a| 
包含磁碟區之磁碟區群組的RAID層級。有效值包括「0」、「1」、「3」、「5」或「6」。



 a| 
「userLabel」
 a| 
您要為新Volume群組指定的名稱。將Volume群組名稱括在雙引號（""）內。



 a| 
「DiveMediaType」
 a| 
要用於Volume群組的磁碟機媒體類型

當儲存陣列中有多種磁碟機媒體類型時、您必須使用此參數。

這些磁碟機媒體有效：

* "HDD"（HDD）-如果磁碟機匣中有硬碟機、請使用此選項
* 「SD」-如果磁碟機匣中有固態磁碟機、請使用此選項
* "unknown"（未知）-如果您不確定磁碟機匣中有哪些類型的磁碟機媒體、請使用此選項
* "ALLMEDIA"（ALLMEDIA）-如果您想要使用磁碟機匣中的所有磁碟機媒體類型、請使用此選項




 a| 
「DiveType」
 a| 
要在Volume群組中使用的磁碟機類型。您無法混用磁碟機類型。

當儲存陣列中有多種磁碟機時、您必須使用此參數。

這些磁碟機類型有效：

* 「as」
* 《NVMe4K》


如果您未指定磁碟機類型、則程式碼不會驗證指定的磁碟機是否屬於此磁碟機類型。



 a| 
「TrayLossProtect」
 a| 
在建立Volume群組時、強制執行「磁碟匣遺失保護」的設定。若要強制執行紙匣遺失保護、請將此參數設為「true」。預設值為「假」。



 a| 
《DrawerLosProtect》
 a| 
當您建立Volume群組時、會執行藥櫃遺失保護的設定。若要強制執行藥櫃遺失保護、請將此參數設為「true」。預設值為「假」。



 a| 
「生態類型」
 a| 
此設定可在建立磁碟區群組及所有相關磁碟區時、指定安全性層級。這些設定有效：

* 「無」-磁碟區群組和磁碟區不安全。
* 「Capable」（功能）：磁碟區群組和磁碟區可以設定安全性、但尚未啟用安全性。
* 「已啟用」-磁碟區群組和磁碟區已啟用安全功能。




 a| 
"REsourceProvisioningCapable（資源配置資源可）"
 a| 
指定是否啟用資源資源配置功能的設定。若要停用資源資源配置、請將此參數設為「假」。預設值為「true」。

|===


== 磁碟機與磁碟區群組

Volume群組是一組磁碟機、由儲存陣列中的控制器邏輯分組。磁碟區群組中的磁碟機數量是RAID層級和控制器韌體的限制。建立Volume群組時、請遵循下列準則：

* 從韌體版本7.10開始、您可以建立一個空的Volume群組、以便保留容量供日後使用。
* 您無法在單一磁碟區群組中混用磁碟機類型。
* 您無法在單一磁碟區群組中混用HDD和SSD磁碟機。
* Volume群組中的磁碟機數量上限取決於下列條件：
+
** 控制器類型
** RAID層級


* RAID級別包括：0、1、3、5和6。
+
** 具有RAID層級3、RAID層級5或RAID層級6的Volume群組不能有超過30個磁碟機。
** RAID層級6的Volume群組必須至少有五個磁碟機。
** 如果RAID層級1的Volume群組有四個以上的磁碟機、儲存管理軟體會自動將Volume群組轉換成RAID層級10、亦即RAID層級1 + RAID層級0。


* 若要啟用紙匣/藥櫃遺失保護、請參閱下表以瞭解其他條件：


|===
| 層級 | 紙匣遺失保護的準則 | 所需的最小紙匣數量 


 a| 
"尖碑池"
 a| 
單一磁碟匣中的磁碟集區不含兩個以上的磁碟機
 a| 
6.



 a| 
《RAID 6》
 a| 
磁碟區群組在單一磁碟匣中不含兩個以上的磁碟機
 a| 
3.



 a| 
「RAID 3」或「RAID 5」
 a| 
磁碟區群組中的每個磁碟機都位於獨立的磁碟匣中
 a| 
3.



 a| 
RAID 1
 a| 
RAID 1配對中的每個磁碟機都必須位於獨立的磁碟匣中
 a| 
2.



 a| 
"RAID 0"
 a| 
無法達到紙匣遺失保護。
 a| 
不適用

|===
|===
| 層級 | 藥櫃損失保護條件 | 所需的藥櫃數量下限 


 a| 
"尖碑池"
 a| 
此集區包含來自所有五個抽取器的磁碟機、每個抽取器中的磁碟機數量相同。如果磁碟集區包含15、20、25、30、35、 40、45、50、55或60個磁碟機。
 a| 
5.



 a| 
《RAID 6》
 a| 
磁碟區群組在單一藥櫃中不包含兩個以上的磁碟機。
 a| 
3.



 a| 
「RAID 3」或「RAID 5」
 a| 
磁碟區群組中的每個磁碟機都位於獨立的磁碟櫃中。
 a| 
3.



 a| 
RAID 1
 a| 
鏡射配對中的每個磁碟機都必須位於獨立的抽屜中。
 a| 
2.



 a| 
"RAID 0"
 a| 
無法達到藥櫃損失保護。
 a| 
不適用

|===


== 熱備援

利用Volume群組、保護資料的重要策略是將儲存陣列中的可用磁碟機指派為熱備援磁碟機。熱備援磁碟機不含資料、可在RAID 1、RAID 3、RAID 5或RAID 6 Volume群組中、作為儲存陣列的待命磁碟機。熱備援可為儲存陣列增加另一層備援。

一般而言、熱備援磁碟機的容量必須等於或大於其所保護磁碟機的已用容量。熱備援磁碟機必須具有相同的媒體類型、相同的介面類型、以及與其保護磁碟機相同的容量。

如果儲存陣列中的磁碟機故障、則熱備援磁碟機通常會自動取代故障磁碟機、而不需要您的介入。如果某個熱備援磁碟機故障時可用、則控制器會使用備援資料同位元檢查、將資料重建到熱備援磁碟機上。資料清空支援也可在軟體將磁碟機標示為「故障」之前、將資料複製到熱備援磁碟機。

實體更換故障磁碟機之後、您可以使用下列任一選項來還原資料：

當您更換故障磁碟機時、熱備援磁碟機的資料會複製回更換磁碟機。此動作稱為「反向複製」。

如果您將熱備援磁碟指定為磁碟區群組的永久成員、則不需要複製作業。

磁碟區群組的磁碟匣遺失保護和藥櫃遺失保護的可用度取決於磁碟區群組所在磁碟機的位置。由於磁碟機故障和熱備援磁碟機的位置、因此可能會遺失磁碟匣遺失保護和藥櫃遺失保護。為了確保紙匣遺失保護和藥櫃遺失保護不受影響、您必須更換故障的磁碟機、以啟動回寫程序。

儲存陣列會自動選取支援Data Assurance（DA）的磁碟機、以進行啟用DA的磁碟區的熱備援涵蓋範圍。

請確定儲存陣列中有支援DA的磁碟機、以提供啟用DA的磁碟區的熱備援涵蓋範圍。如需具備DA功能磁碟機的詳細資訊、請參閱資料保證功能。

安全功能（FIPS和FDE）磁碟機可作為熱備援、用於具有安全功能和不安全功能的磁碟機。不安全的磁碟機可為其他不安全的磁碟機提供涵蓋範圍、如果磁碟區群組未啟用安全功能、則可為具有安全功能的磁碟機提供涵蓋範圍。FIPS Volume群組只能使用FIPS磁碟機作為熱備援磁碟機；不過、您可以使用FIPS熱備援磁碟機作為不安全、安全且安全的磁碟區群組。

如果您沒有熱備援磁碟機、您仍可在儲存陣列運作時更換故障磁碟機。如果磁碟機是RAID 1、RAID 3、RAID 5或RAID 6 Volume群組的一部分、則控制器會使用備援資料同位元檢查、自動將資料重新建置到替換磁碟機上。此行動稱為「重建」。



== 區段大小

區段大小決定控制器在磁碟區中的單一磁碟機上寫入多少資料區塊、然後再將資料寫入下一個磁碟機。每個資料區塊儲存512個位元組的資料。資料區塊是最小的儲存單位。區段的大小決定其包含多少資料區塊。例如、8-KB區段可容納16個資料區塊。64 KB區段可容納128個資料區塊。

當您輸入區段大小的值時、會對照控制器在執行時間提供的支援值來檢查該值。如果您輸入的值無效、控制器會傳回有效值清單。使用單一磁碟機進行單一要求時、其他磁碟機仍可同時處理其他要求。如果磁碟區位於單一使用者正在傳輸大量資料（例如多媒體）的環境中、則當單一資料傳輸要求以單一資料等量磁碟區來處理時、效能就會達到最大化。（資料等量磁碟區是區段大小乘以磁碟區群組中用於資料傳輸的磁碟機數量。） 在此情況下、多個磁碟機用於相同的要求、但每個磁碟機只能存取一次。

若要在多使用者資料庫或檔案系統儲存環境中達到最佳效能、請設定區段大小、將滿足資料傳輸要求所需的磁碟機數量降至最低。



== 使用提示

[NOTE]
====
您不需要輸入「cacheReadPrefetch」參數或「Size」參數的值。如果不輸入值、控制器韌體會使用「usageHint」參數、並將「FileSystem」作為預設值。輸入「usageHint」參數的值、以及「cacheReadPrefetch」參數的值、或輸入「SizeDE」參數的值、都不會造成錯誤。您為「cacheReadPrefetch」參數或「Size」參數輸入的值優先於「usageHint」參數的值。下表顯示各種使用提示的區段大小和快取讀取預先擷取設定：

====
|===
| 使用提示 | 區段大小設定 | 動態快取讀取預先擷取設定 


 a| 
檔案系統
 a| 
128 KB
 a| 
已啟用



 a| 
資料庫
 a| 
128 KB
 a| 
已啟用



 a| 
多媒體
 a| 
256 KB
 a| 
已啟用

|===


== 快取讀取預先擷取

快取讀取預先擷取可讓控制器在控制器讀取及複製主機從磁碟機要求的資料區塊時、將其他資料區塊複製到快取中。此動作可增加日後從快取執行資料要求的機會。對於使用循序資料傳輸的多媒體應用程式而言、快取讀取預先擷取非常重要。「cacheReadPrefetch」參數的有效值為「true」或「假」。預設值為「true」。



== 安全類型

使用「安全性類型」參數來指定儲存陣列的安全性設定。

您必須先建立儲存陣列安全性金鑰、才能將「安全性類型」參數設定為「已啟用」。使用「create storageArray SECURITY Key」命令建立儲存陣列安全金鑰。這些命令與安全金鑰有關：

* 「create storageArray securityKey」
* 「匯出storageArray安全金鑰」
* 「Import storageArray securityKey」
* 「et storageArray安全性金鑰」
* 「啟用volumeGroup [volumeGroupName]安全性」
* 「啟用diskPool [diskPoolName] Security」




== 安全磁碟機

安全的磁碟機可以是全磁碟加密（FDE）磁碟機、也可以是聯邦資訊處理標準（FIPS）磁碟機。使用「RecureDrives」參數指定要使用的安全磁碟機類型。您可以使用的值是「FIPS」和「FDE」。



== 資料保證管理

資料保證（DA）功能可提升整個儲存系統的資料完整性。DA可讓儲存陣列檢查資料在主機和磁碟機之間移動時可能發生的錯誤。啟用此功能時、儲存陣列會將錯誤檢查代碼（也稱為循環備援檢查或CRC）附加到磁碟區中的每個資料區塊。資料區塊移動之後、儲存陣列會使用這些CRC代碼來判斷傳輸期間是否發生任何錯誤。可能毀損的資料既不會寫入磁碟、也不會傳回主機。

如果您想要使用DA功能、請從僅包含支援DA磁碟機的集區或磁碟區群組開始。然後建立具有DA功能的磁碟區。最後、請使用能夠執行DA的I/O介面、將這些具有DA功能的磁碟區對應至主機。具備DA功能的I/O介面包括Fibre Channel、SAS和iSER over InfiniBand（適用於RDMA/IB的iSCSI擴充功能）。以太網iSCSI或InfiniBand上的SRP不支援DA。

[NOTE]
====
當所有磁碟機都具備DA功能時、您可以將「datAssurance」參數設定為「啟用」、然後在特定作業中使用DA。例如、您可以建立包含具有DA功能磁碟機的磁碟區群組、然後在啟用DA的磁碟區群組中建立磁碟區。使用啟用DA的磁碟區的其他作業也有支援DA功能的選項。

====
如果「data Assurance」參數設為「啟用」、則僅會考慮磁碟區候選磁碟機的資料保證功能；否則、將會考慮具備資料保證功能的磁碟機和不具備資料保證功能的磁碟機。如果只有可用的資料保證磁碟機、則會使用啟用的資料保證磁碟機來建立新的Volume群組。



== 最低韌體層級

7.10.

7.50新增「最安全類型」參數。

7.60新增「drawerID」使用者輸入、「driveMediaType」參數及「drawerLosProtect」參數。

7.75新增了「data Assurance」參數。

8.63新增了「資源配置資源Capable」參數。
