---
permalink: commands-a-z/create-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: create, asynchronous, mirror, group 
summary: create asyncdMirrorGroup命令會在本機儲存陣列和遠端儲存陣列上建立新的空非同步鏡射群組。 
---
= 建立非同步鏡射群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「create asyncdMirrorGroup」命令會在本機儲存陣列和遠端儲存陣列上建立一個新的空非同步鏡射群組。



== 支援的陣列

此命令適用於任何個別儲存陣列、但有一些限制。如果您在E2700或E5600陣列上執行命令、則沒有任何限制。

[NOTE]
====
E4000 ， E2800 ， E5700 ， EF600 和 EF300 平台不支援此命令。

====


== 角色

不適用



== 背景

非同步鏡射群組是一個容器、可容納多個鏡射配對、以便將它們當成一個實體進行管理。您可以建立非同步鏡射群組、為群組中的所有鏡射配對定義同步處理設定。非同步鏡射群組中的每個鏡射配對都會共用相同的同步處理設定、主要和次要角色、以及寫入模式。

非同步鏡射群組與用於鏡射的本機儲存陣列和遠端儲存陣列相關聯。本機儲存陣列是非同步鏡射群組的主要端點、而遠端儲存陣列則是非同步鏡射群組的次要端點。新增至本機儲存陣列之非同步鏡射群組的所有磁碟區、都會在鏡射關係中扮演主要角色。之後、新增至遠端儲存陣列非同步鏡射群組的所有磁碟區、都會在鏡射關係中擔任次要角色。

請確定您在本機儲存陣列上執行「Create Asynsynsynror Group」（建立非同步鏡射群組）命令。非同步鏡射群組建立是從儲存陣列啟動、其中包含在鏡射關係中擔任主要角色的磁碟區。您可以使用「Create Asynsynror Group」（建立非同步鏡射群組）命令、指定遠端儲存陣列的身分識別、該陣列包含在鏡射關係中擔任次要角色的磁碟區。



== 語法

[source, cli, subs="+macros"]
----
create asyncMirrorGroup userLabel=pass:quotes[_"asyncMirrorGroupName"_]
(remoteStorageArrayName=pass:quotes[_"storageArrayName"_] | remoteStorageArrayWWN=pass:quotes[_"wwID"_])
[remotePassword=pass:quotes[_"password"_]
interfaceType=(FC | iSCSI)
[syncInterval=pass:quotes[_integer_](minutes | hours | days)]
[warningSyncThreshold=pass:quotes[_integer_](minutes | hours | days)]
[warningRecoveryThreshold=pass:quotes[_integer_](minutes | hours | days)]
[warningThresholdPercent=pass:quotes[_percentValue_]]
[autoResync=(TRUE | FALSE)]
----


== 參數

|===
| 參數 | 說明 


 a| 
「userLabel」
 a| 
您要建立的新非同步鏡射群組名稱。將新的非同步鏡射群組名稱以雙引號（""）括住。

此名稱在本機和遠端儲存陣列上必須是唯一的。



 a| 
"REmoteStorageArrayName"
 a| 
鏡射非同步鏡射群組的遠端儲存陣列名稱。將儲存陣列名稱括在雙引號（""）內。

遠端儲存陣列的連線類型必須與本機儲存陣列相同。



 a| 
"REmoteStorageArrayWWW"
 a| 
鏡射非同步鏡射群組之遠端儲存陣列的全球識別碼（WWID）。您可以使用WWID而非儲存陣列名稱來識別儲存陣列。將WWID括在尖括弧內（<>）。

遠端儲存陣列的連線類型必須與本機儲存陣列相同。



 a| 
「即時密碼」
 a| 
遠端儲存陣列的密碼。當遠端儲存陣列受到密碼保護時、請使用此參數。將密碼括在雙引號（""）內。



 a| 
「介面類型」
 a| 
指定要使用的連線類型：Fibre Channel Fabric或iSCSI介面。（預設為Fibre Channel。） 本機儲存陣列和遠端儲存陣列必須透過適當的光纖通道架構或iSCSI介面來連接。



 a| 
《yncdal區間》
 a| 
指定從本機儲存陣列自動傳送修改資料更新至遠端儲存陣列之間的時間長度。您可以指定時間長度（以分鐘、小時或天為單位）。

[NOTE]
====
請勿在整數與時間長度之間加入空格。

====
例如：「10分鐘」



 a| 
《warningSyncThreshold》
 a| 
指定在非同步鏡射群組中所有磁碟區的同步處理時間超過所定義時間的情況下、等待警示觸發的時間長度。您可以指定時間長度（以分鐘、小時或天為單位）。

[NOTE]
====
請勿在整數與時間長度之間加入空格。

====
例如：「30分鐘」



 a| 
《warningRecoveryThreshold》（警告恢復臨界值）
 a| 
指定當遠端儲存陣列上時間點映像的自動資料更新時間早於定義的時間時、等待警示觸發的時間長度。定義從上次更新結束的臨界值。您可以指定時間長度（以分鐘、小時或天為單位）。

[NOTE]
====
您必須將恢復點臨界值設定為同步處理時間間隔臨界值的兩倍。

====
[NOTE]
====
請勿在整數與時間長度之間加入空格。

====
例如：「60分鐘」



 a| 
《warningTholholdPercent
 a| 
指定鏡射儲存庫磁碟區的容量達到定義的百分比時、等待警示觸發的時間長度。依剩餘容量百分比（%）定義臨界值。



 a| 
自動重新同步
 a| 
在非同步鏡射群組中、自動重新同步主要磁碟區與非同步鏡射配對的次要磁碟區的設定。此參數具有下列值：

* 「已啟用」-自動重新同步已開啟。您不需要進一步執行任何動作、就能重新同步主要Volume和次要Volume。
* 「停用」—自動重新同步功能已關閉。若要重新同步主磁碟區和次磁碟區、您必須執行「假定同步同步鏡射群組」命令。


|===


== 附註

* 必須在用於鏡射活動的本機和遠端儲存陣列上啟用和啟動非同步鏡射功能。
* 您可以使用字母數字字元、連字號和底線的任意組合來命名。名稱最多可包含30個字元。
* 本機與遠端儲存陣列必須透過光纖通道架構或iSCSI介面來連接。
* 密碼會儲存在管理網域中的每個儲存陣列上。如果先前未設定密碼、則不需要密碼。密碼可以是字母數字字元的任意組合、最多30個字元。（您可以使用「set storageArray」命令來定義儲存陣列密碼。）
* 視組態而定、您可以在儲存陣列上建立最多的非同步鏡射群組。
* 非同步鏡射群組會建立為空白、而鏡射配對稍後會新增至這些群組。只能將鏡射配對新增至非同步鏡射群組。每個鏡射配對只會與一個非同步鏡射群組相關聯。
* 非同步鏡射程序是在定義的同步時間間隔內啟動。定期時間點映像會複寫、因為只會複製變更的資料、而不會複製整個Volume。




== 最低韌體層級

7.84

11.80 新增 EF600 和 EF300 陣列支援
