---
permalink: commands-a-z/create-read-only-snapshot-volume.html 
sidebar: sidebar 
keywords: create, read only, snapshot, volume 
summary: create snapVolume命令會為基礎Volume的快照映像建立唯讀快照磁碟區。若要將唯讀快照磁碟區變更為讀寫磁碟區、請使用set snapVolume convertToReadWrite命令。 
---
= 建立唯讀快照磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「create snapVolume」命令會為基礎磁碟區的快照映像建立唯讀快照磁碟區。若要將唯讀快照磁碟區變更為讀寫磁碟區、請使用「set snapVolume convertToReadWrite」命令。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

[NOTE]
====
您無法將此命令用於線上Volume複本中使用的快照映像。

====


== 語法

[source, cli, subs="+macros"]
----
create snapVolume userLabel=pass:quotes[_"snapVolumeName"_
snapImageID="_snapCGID:imageID"_]
readOnly
----


== 參數

|===
| 參數 | 說明 


 a| 
「userLabel」
 a| 
您要指定給快照磁碟區的名稱。將快照磁碟區名稱括在雙引號（""）內。



 a| 
「napImageID」
 a| 
您要新增至新唯讀快照磁碟區的快照映像名稱。快照映像的名稱由兩部分組成：

* 快照群組的名稱
* 快照群組中快照映像的識別碼


快照映像的識別碼可以是下列其中一項：

* 整數值、即快照群組中快照的順序編號。
* 「最新」：如果您想要顯示快照群組中建立的最新快照映像、請使用此選項。
* 「最舊」：如果您想要顯示快照群組中建立的最早快照映像、請使用此選項。


將快照映像名稱括在雙引號（""）內。



 a| 
"REadOnly"
 a| 
此參數會將Snapshot Volume設為唯讀。此參數實際上是布林值、但在這個命令的內容中、布林值永遠是「true」。

[NOTE]
====
使用"REadOnly"參數時、不會建立Snapshot Volume。

====
|===


== 附註

您可以使用字母數字字元、底線（_）、連字號（-）和井號（#）的任意組合來命名。名稱最多可包含30個字元。

快照映像的識別碼有兩個部分以分號分隔（：）：

* 快照群組的名稱
* 快照映像的識別碼


例如、如果您要使用快照群組中名稱為snapGroup1的最新快照映像、建立名為engData1的唯讀磁碟區、請使用下列命令：

[listing]
----
create snapVolume userLabel="engData1" snapImageID="snapGroup1:newest" readOnly;
----


== 最低韌體層級

7.83
