---
permalink: commands-a-z/create-storagearray-securitykey.html 
sidebar: sidebar 
keywords: create, storage, array, security, key 
summary: create storageArray securityKey命令可為具有完整磁碟加密（FDE）磁碟機的儲存陣列建立或變更新的安全金鑰。 
---
= 建立儲存陣列安全金鑰
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「create storageArray SECURITY Key」命令可為具有完整磁碟加密（FDE）磁碟機的儲存陣列建立或變更新的安全金鑰。



== 支援的陣列

如果啟用外部金鑰管理，則此命令僅適用於 E4000 ， E2800 ， E5700 ， EF600 和 EF300 陣列。如果已啟用內部金鑰管理、則只要安裝所有SMcli套件、該命令就會套用至任何個別的儲存陣列。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有安全管理角色。



== 背景

對於內部金鑰管理、此命令可啟用內部金鑰管理功能並建立安全金鑰。建立金鑰之後、請使用「show storageArray securityKey」命令來使用金鑰。此命令也可用於變更安全性金鑰。

對於外部金鑰管理、此命令會建立不同的金鑰、以取代您啟用此功能時最初建立的金鑰。使用「enable storageArray externalKeyManagement」命令來啟用外部金鑰管理功能、並建立初始安全金鑰。此命令也可用於變更安全性金鑰。



== 語法

[source, cli, subs="+macros"]
----
create storageArray securityKey
[keyIdentifier=pass:quotes[_"keyIdentifierString"_]]
passPhrase=pass:quotes[_"passPhraseString"_
file=_"fileName"_]
[commitSecurityKey=(TRUE | FALSE)]
----


== 參數

|===
| 參數 | 說明 


 a| 
「KeyIdentifier」-僅適用於內部金鑰管理
 a| 
您可以讀取的字元字串、是圍繞安全性金鑰的包裝函式。將金鑰識別碼括在雙引號（""）內。

您可以輸入內部安全金鑰的金鑰識別碼字元、以協助您日後識別金鑰。以下是格式化規則：

* 金鑰識別碼最多可輸入189個英數字元。金鑰識別碼不能包含下列字元：
+
** 空間
** 標點符號
** 符號


* 如果您沒有輸入內部金鑰的「keyIdentfer」參數、控制器會自動產生「keyIdentfer」參數。


系統會自動產生其他字元、並附加到您輸入的金鑰識別碼字串結尾。如果您沒有為「Keyidentifier'」參數輸入任何字串、則金鑰識別碼只會由自動產生的字元組成。

[NOTE]
====
外部金鑰管理會忽略此參數、因為金鑰識別碼會完全自動產生。如果儲存陣列有使用者標籤、則此自動產生的字串會由字元「a'（每年）」、接著是儲存陣列使用者標籤、儲存陣列識別碼、以及隨機產生的字串組成。使用者標籤中任何非英數字元的字元、都會轉換成底線（`_`）字元。例如、abc#8的使用者標籤會先轉換成「s rabc_8」、再預先加上其他金鑰識別碼。對於沒有使用者標籤的儲存陣列、金鑰識別碼是由儲存陣列識別碼和隨機產生的字串所組成。

====


 a| 
《通關密碼》
 a| 
加密安全金鑰的字元字串、以便將安全金鑰儲存在外部檔案中。將密碼括在雙引號（""）內。

如需建立有效密碼的正確格式資訊、請參閱本命令說明中的附註。

您的通關密碼必須符合下列條件：

* 長度必須介於8到32個字元之間。
* 不得包含空白。
* 必須包含至少一個大寫字母。
* 必須包含至少一個英文字母。
* 必須包含至少一個數字。
* 必須包含至少一個非英數字元、例如<>@+。


[NOTE]
====
如果您的密碼不符合這些條件、您將會收到錯誤訊息、並會要求您重試命令。

====


 a| 
檔案
 a| 
您要儲存安全性金鑰的檔案路徑和檔案名稱。例如：

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
檔案名稱的副檔名必須為「.slk」。

====
將檔案路徑和名稱括在雙引號（""）內。



 a| 
「commitSecurity Key」-僅適用於內部金鑰管理
 a| 
此參數會將安全金鑰提交給所有FDE磁碟機和控制器的儲存陣列。提交安全金鑰之後、必須有金鑰才能存取儲存陣列中「啟用安全性」磁碟機上的資料。只能使用金鑰來讀取或變更資料、而且磁碟機絕不能在不安全的模式下使用、否則資料就無法使用或完全清除磁碟機。

預設值為假。如果此參數設為假、請傳送另一個「set storageArray SECURITY Key」命令、將安全金鑰提交給儲存陣列。

|===


== 最低韌體層級

7.40、引進內部金鑰管理

8.40、推出外部金鑰管理
