---
permalink: commands-a-z/create-snapgroup.html 
sidebar: sidebar 
keywords: create, snapshot, group 
summary: create snapGroup命令會建立新的快照群組及相關的儲存庫Volume。 
---
= 建立快照群組 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「create snapGroup」命令會建立新的快照群組和相關的儲存庫Volume。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

快照群組包含相關基礎Volume的一系列快照映像。快照群組具有儲存庫磁碟區、可用來儲存屬於快照群組一部分之所有快照映像的資料。

[NOTE]
====
在建立快照群組之前、請先確定可用容量的磁碟區群組可供使用。

====


== 語法

[source, cli, subs="+macros"]
----
create snapGroup userLabel=pass:quotes[_"snapGroupName_" sourceVolume=_"volumeName"_]
[(repositoryVolume="repos_xxxx" |
repositoryVolume=(pass:quotes[_volumeGroupName_] [capacity=capacityValue]) |
repositoryVolume=(pass:quotes[_diskPoolName_] [capacity=capacityValue]))]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[rollbackPriority=(highest | high | medium | low | lowest)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]|
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapshotSchedule_)]]
----


== 參數

|===
| 參數 | 說明 


 a| 
「userLabel」
 a| 
您要為新快照群組指定的名稱。將快照群組識別碼括在雙引號（""）內。



 a| 
「ourceVolume」
 a| 
您要用作快照映像來源的磁碟區名稱。將來源磁碟區名稱括在雙引號（""）內。



 a| 
「repositoryVolume」
 a| 
儲存庫磁碟區的名稱、該磁碟區將包含快照群組的變更資料。

您有兩個選項可以定義儲存庫Volume的名稱：

* 使用現有的儲存庫Volume：名稱
* 執行此命令時、請建立新的儲存庫Volume


現有儲存庫磁碟區的名稱由兩部分組成：

* 「錯誤」一詞
* 儲存管理軟體指派給儲存庫Volume名稱的四位數數字識別碼


將現有儲存庫磁碟區的名稱以雙引號（""）括住。

若要在執行此命令時建立新的儲存庫磁碟區、您必須輸入要儲存庫磁碟區的磁碟區群組或磁碟集區名稱。或者、您也可以定義儲存庫Volume的容量。如果您想要定義容量、可以使用下列值：

* 整數值、代表基本Volume容量的百分比
* 表示基本Volume容量百分比的小數位值
* 儲存庫磁碟區的特定大小。大小的定義單位為「位元組」、「KB」、「MB」、「GB」或「TB」。


如果您不使用容量選項、儲存管理軟體會將容量設定為基礎Volume容量的20%。

當您執行此命令時、儲存管理軟體會為快照Volume建立儲存庫磁碟區。



 a| 
「repositoryFullPolicy」
 a| 
定義當快照群組儲存庫磁碟區已滿時、快照映像處理的繼續方式。您可以選擇將I/O寫入失敗至儲存庫磁碟區的基礎磁碟區（「故障基礎寫入器」）、或刪除（清除）儲存庫磁碟區中的快照映像（「PurgeSnapImages」）。「pugeSnapImages」選項會刪除最舊的快照映像、以釋放空間。預設動作為「pugeSnapImages」。



 a| 
「復原優先順序」
 a| 
決定是否應將系統資源分配給復原作業、而犧牲系統效能。值「高」表示復原作業的優先順序高於所有其他主機I/O值「low」表示復原作業應在對主機I/O影響最小的情況下執行預設值為「管理」。



 a| 
「repositoryFullLimit」
 a| 
您收到快照群組儲存庫磁碟區即將滿警示的儲存庫容量百分比。使用整數值。例如、值70表示70%。預設值為75。



 a| 
「自動刪除限制」
 a| 
每個快照群組均可設定為自動刪除其快照映像、以將快照群組中的快照映像總數維持在指定層級或以下。啟用此選項後、每當在快照群組中建立新的快照映像時、系統會自動刪除群組中最舊的快照映像、以符合限制值。此動作可釋出儲存庫容量、以便用於滿足後續快照映像的寫入時複製需求。



 a| 
「enableSchedule」
 a| 
使用此參數可開啟或關閉排程快照作業的功能。若要開啟快照排程、請將此參數設為「true」。若要關閉快照排程、請將此參數設為「假」。

|===


== 附註

每個快照群組名稱都必須是唯一的。您可以使用任何字母數字字元、底線（_）、連字號（-）和井號（#）的組合作為使用者標籤。使用者標籤最多可有30個字元。

若要建立快照群組、您必須有相關聯的儲存庫磁碟區、以便儲存快照映像。您可以使用現有的儲存庫磁碟區、或是建立新的儲存庫磁碟區。您可以在建立快照群組時建立儲存庫磁碟區。Snapshot群組儲存庫Volume是可擴充的Volume、其結構是最多16個標準Volume實體的串聯集合。一開始、可擴充的儲存庫磁碟區只有一個元素。可擴充儲存庫磁碟區的容量與單一元素的容量完全相同。您可以附加額外的標準磁碟區、以增加可擴充儲存庫磁碟區的容量。然後、複合式可擴充儲存庫的Volume容量會成為所有串聯標準磁碟區容量的總和。

根據每個快照映像的建立時間、快照群組對快照映像有嚴格的排序順序。在另一個快照映像之後建立的快照映像、是相對於該其他快照映像的_後續_。在另一個快照映像之前建立的快照映像是與另一個快照映像相對的_前身。

快照群組儲存庫磁碟區必須滿足下列總和的最低容量需求：

* 32 MB、可支援快照群組和寫入時複製處理的固定負荷。
* 復原處理的容量、是基礎Volume容量的1/5000。


控制器韌體和儲存管理軟體會強制執行最小容量。

當您第一次建立快照群組時、它不包含任何快照映像。建立快照映像時、您可以將快照映像新增至快照群組。使用「create SnapImage」命令建立快照映像、並將快照映像新增至快照群組。

快照群組可以具有下列其中一種狀態：

* *最佳*：快照群組正常運作。
* *完整*：快照群組儲存庫已滿。無法執行其他寫入時複製作業。此狀態僅適用於儲存庫完整原則設定為失敗基礎寫入的快照群組。處於完整狀態的任何快照群組、都會針對儲存陣列張貼需要注意的條件。
* *超過臨界值*：快照群組儲存庫磁碟區使用量達到或超過其警示臨界值。此狀態下的任何快照群組都會導致儲存陣列出現「Needs－Attention（需要注意）」狀況。
* *故障*：快照群組發生問題、導致快照群組中的所有快照映像無法使用。例如、特定類型的儲存庫磁碟區故障可能會導致「失敗」狀態。若要從「失敗」狀態中恢復、請使用「快照群組」命令。


您可以使用「autodeleteLimit」參數、將每個快照群組設定為自動刪除快照映像。自動刪除快照映像可讓您避免例行性地手動刪除不想要的映像、而且因為儲存庫磁碟區已滿、可能會導致無法建立未來的快照映像。當您使用「AutoDelete限制」參數時、儲存管理軟體會從最舊的開始自動刪除快照映像。儲存管理軟體會刪除快照映像、直到快照映像達到與您使用「autodeleteLimit」參數輸入的數字相同的數個快照映像為止。將新的快照映像新增至儲存庫磁碟區時、儲存管理軟體會刪除最舊的快照映像、直到達到「自動刪除限制」參數編號為止。

「enableschedule」參數和「排程」參數可讓您排程建立快照群組的快照映像。使用這些參數、您可以排程每天、每週或每月快照（按日或依日期）。「enableschedule」參數會開啟或關閉排程快照的功能。啟用排程時、您可以使用「排程」參數來定義快照發生的時間。

下表說明如何使用「排程」參數的選項：

|===
| 參數 | 說明 


 a| 
「排程」
 a| 
指定排程參數所需。



 a| 
《立即》
 a| 
立即啟動作業。此項目與任何其他排程參數互不相關。



 a| 
「enableSchedule」
 a| 
如果設定為「true」、排程功能就會開啟。如果設定為「假」、排程功能就會關閉。

[NOTE]
====
預設值為「假」。

====


 a| 
「TartDate」
 a| 
開始操作的特定日期。輸入日期的格式為MM：DD：年。預設為目前日期。此選項的範例為「最新日期=06:27:11」。



 a| 
「排定第二天」
 a| 
一週中開始營運的一天。可以是下列全部或一或多個值：

* 《當日》
* 《星期二》
* 《星期三》
* 《週四》
* 《星期五》
* 《星期六》
* 《今日》


[NOTE]
====
將值括在括弧中。例如、「排定日=（星期三）」。

====
可以指定多天、方法是將天數以一組括弧括住、並以空格分隔每天。例如、「排定日=（週一週三週五）」。

[NOTE]
====
此參數與每月排程不相容。

====


 a| 
「時間」
 a| 
一天中開始操作的時間。輸入時間的格式為hh：mm、其中hh是小時、公釐是小時的分鐘數。使用24小時時鐘。例如下午2：00為14：00。此選項的範例為「最晚時間=14：27」。



 a| 
「排定時間間隔」
 a| 
在兩次作業之間至少要有一段時間（以分鐘為單位）。排程時間間隔不應超過1440（24小時）、且應為30的倍數。

此選項的範例為「排定時間間隔=180」。



 a| 
「結束日期」
 a| 
停止作業的特定日期。輸入日期的格式為MM：DD：年。如果不需要結束日期、您可以指定「noEndDate」。此選項的範例為「endDat=11：26：11」。



 a| 
《時程PerDay》
 a| 
一天內執行作業的次數。此選項的範例為「timesPerDay = 4」。



 a| 
《時區》
 a| 
指定排程所使用的時區。可透過兩種方式指定：

* *格林尼治標準時間（格林尼治標準時間
+
時區與GMT.的偏移量。範例：「ezone = GMT-06：00」。

* *文字字串*
+
標準時區文字字串、必須以引號括住。範例：'TimeZone="America/芝加哥"`





 a| 
「排定日期」
 a| 
執行作業的月份中的某一天。天數的值為數字、範圍為1-31。

[NOTE]
====
此參數與每週排程不相容。

====
「排定日期」選項的範例是「排定日期=（15）」。



 a| 
《我的》
 a| 
執行作業的特定月份。月份的值包括：

* 「一月」-一月
* 2月
* 「馬爾」-三月
* 4月
* 「我」-五月
* 《君》- 6月
* 「7月」- 7月
* 「8月」- 8月
* 9月
* 「oct」- 10月
* 「NOV」- 11月
* 「DEC」- 12月


[NOTE]
====
將值括在括弧中。例如、「montth=（JAN）」。

====
您可以將月份以一組括弧括住、並以空格分隔每個月、藉此指定一個以上的月份。例如、「month =（1月7月12日）」。

使用此參數搭配「排定日期」參數、即可在每月的特定日期執行作業。

[NOTE]
====
此參數與每週排程不相容。

====
|===
下表說明如何使用「時區（TimeZone）參數：

|===
| 時區名稱 | GMT偏 移 


 a| 
"etc/GMT+12"
 a| 
「GMT-12：00」



 a| 
"etc/GMT+11"
 a| 
「GMT-11：00」



 a| 
《太平洋/火努魯魯魯》
 a| 
「GMT- 10：00」



 a| 
《美洲/安克雷奇》
 a| 
「GMT-09：00」



 a| 
《美洲/聖達伊莎貝爾》
 a| 
「GMT-08：00」



 a| 
《美洲/洛杉磯》
 a| 
「GMT-08：00」



 a| 
《美洲/鳳凰》
 a| 
「GMT-07：00」



 a| 
《美洲/奇瓦瓦》
 a| 
「GMT-07：00」



 a| 
《美洲/丹佛》
 a| 
「GMT-07：00」



 a| 
《美洲/危地馬拉》
 a| 
「GMT-06：00」



 a| 
《美國/芝加哥》
 a| 
「GMT-06：00」



 a| 
《美洲/墨西哥市》
 a| 
「GMT-06：00」



 a| 
《美洲/瑞吉娜》
 a| 
「GMT-06：00」



 a| 
《美洲/波哥大》
 a| 
「GMT-05：00」



 a| 
《美洲/紐約》
 a| 
「GMT-05：00」



 a| 
"etc/GMT+5"
 a| 
「GMT-05：00」



 a| 
《美洲/卡拉卡斯》
 a| 
「GMT-04：30」



 a| 
《美洲/亞松森》
 a| 
「GMT-04：00」



 a| 
《美洲/哈利法克斯》
 a| 
「GMT-04：00」



 a| 
《美洲/庫比亞巴》（America/Cubaba）
 a| 
「GMT-04：00」



 a| 
《美洲/拉和平》
 a| 
「GMT-04：00」



 a| 
《美洲/聖地亞哥》
 a| 
「GMT-04：00」



 a| 
《美洲/聖約翰》
 a| 
「GMT-03：30」



 a| 
《美洲/聖保羅》
 a| 
「GMT-03：00」



 a| 
《美洲/布宜諾斯艾利斯》
 a| 
「GMT-03：00」



 a| 
《美洲/開恩島》
 a| 
「GMT-03：00」



 a| 
《美洲/哥達塔布》
 a| 
「GMT-03：00」



 a| 
《美洲/蒙得維的亞》
 a| 
「GMT-03：00」



 a| 
"etc/GMT+2」
 a| 
「GMT-02：00」



 a| 
《大西洋/亞速爾斯》
 a| 
「GMT-01：00」



 a| 
《大西洋/佛得角》
 a| 
「GMT-01：00」



 a| 
《非洲/卡薩布蘭卡》
 a| 
"GMT"



 a| 
"etc/GMT"
 a| 
"GMT"



 a| 
《歐洲/倫敦》
 a| 
"GMT"



 a| 
《大西洋/雷克雅未克》
 a| 
"GMT"



 a| 
《歐洲/柏林》
 a| 
"GMT+01：00"



 a| 
《歐洲/布达佩斯》
 a| 
"GMT+01：00"



 a| 
《歐洲/巴黎》
 a| 
"GMT+01：00"



 a| 
《歐洲/華沙》
 a| 
"GMT+01：00"



 a| 
《非洲/拉哥斯》
 a| 
"GMT+01：00"



 a| 
《非洲/溫得和克》
 a| 
"GMT+01：00"



 a| 
《亞洲/安曼》
 a| 
"GMT+02：00"



 a| 
《亞洲/貝魯特》
 a| 
"GMT+02：00"



 a| 
《非洲/開羅》
 a| 
"GMT+02：00"



 a| 
《亞洲/大馬士》
 a| 
"GMT+02：00"



 a| 
《非洲/約翰內斯堡》
 a| 
"GMT+02：00"



 a| 
《歐洲/ Kiev》
 a| 
"GMT+02：00"



 a| 
《亞洲/耶路撒冷》
 a| 
"GMT+02：00"



 a| 
《歐洲/伊斯坦堡》
 a| 
"GMT+03：00"



 a| 
《歐洲/明思克》
 a| 
"GMT+02：00"



 a| 
《亞洲/巴格達》
 a| 
"GMT+03：00"



 a| 
《亞洲/利雅德》
 a| 
"GMT+03：00"



 a| 
《非洲/奈洛比》
 a| 
"GMT+03：00"



 a| 
《亞洲/德黑蘭》
 a| 
"GMT+03：30"



 a| 
《歐洲/莫斯科》
 a| 
"GMT+04：00"



 a| 
《亞洲/迪拜》
 a| 
"GMT+04：00"



 a| 
《亞洲/巴庫》
 a| 
"GMT+04：00"



 a| 
《印度/毛里求斯》
 a| 
"GMT+04：00"



 a| 
《亞洲/第比利斯》
 a| 
"GMT+04：00"



 a| 
《亞洲/埃里溫》
 a| 
"GMT+04：00"



 a| 
《亞洲/卡布爾》
 a| 
"GMT+04：30"



 a| 
《亞洲/喀拉多尼亞》
 a| 
"GMT+05：00"



 a| 
《亞洲/塔什干》
 a| 
"GMT+05：00"



 a| 
《亞洲/卡爾庫塔》
 a| 
"GMT+05：30"



 a| 
《亞洲/科倫波》
 a| 
"GMT+05：30"



 a| 
《亞洲/加德滿都》
 a| 
"GMT+05：45"



 a| 
《亞洲/葉卡捷琳堡》
 a| 
"GMT+06:00"



 a| 
《亞洲/阿拉木圖》
 a| 
"GMT+06:00"



 a| 
《亞洲/達卡》
 a| 
"GMT+06:00"



 a| 
《亞洲/蘭果安》
 a| 
"GMT+06:30"



 a| 
《亞洲/新西比爾斯克》
 a| 
"GMT+07：00"



 a| 
《亞洲/曼谷》
 a| 
"GMT+07：00"



 a| 
《亞洲/克拉斯諾亞爾斯克》
 a| 
"GMT+08：00"



 a| 
《亞洲/上海》
 a| 
"GMT+08：00"



 a| 
《亞洲/新加坡》
 a| 
"GMT+08：00"



 a| 
澳洲/珀斯（Australia /珀斯）
 a| 
"GMT+08：00"



 a| 
《亞洲/台北》
 a| 
"GMT+08：00"



 a| 
《亞洲/烏蘭巴塔》
 a| 
"GMT+08：00"



 a| 
《亞洲/伊爾庫次克》
 a| 
"GMT+09：00"



 a| 
《亞洲/東京》
 a| 
"GMT+09：00"



 a| 
《亞洲/首爾》
 a| 
"GMT+09：00"



 a| 
《澳洲/阿得萊德》
 a| 
"GMT+09：30"



 a| 
《澳洲/達爾文》（Australia / Darwin）
 a| 
"GMT+09：30"



 a| 
《亞洲/亞庫次克》
 a| 
"GMT+10：00"



 a| 
《澳洲/布里斯本》
 a| 
"GMT+10：00"



 a| 
《澳洲/雪梨》
 a| 
"GMT+10：00"



 a| 
《太平洋/莫雷斯比港》（Pacific / Port Moresby）
 a| 
"GMT+10：00"



 a| 
《澳洲/荷伯特》
 a| 
"GMT+10：00"



 a| 
《亞洲/符拉迪沃斯託克》
 a| 
"GMT+11：00"



 a| 
《太平洋/瓜達爾卡納爾》
 a| 
"GMT+11：00"



 a| 
《太平洋/奧克蘭》
 a| 
"GMT+12：00"



 a| 
「etc/GMT-12」
 a| 
"GMT+12：00"



 a| 
《太平洋/斐濟》
 a| 
"GMT+12：00"



 a| 
《亞洲/堪察加》
 a| 
"GMT+12：00"



 a| 
《太平洋/通通塔普》
 a| 
"GMT+13：00"

|===
用於定義排程的程式碼字串類似下列範例：

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
如果您也使用「排程時間間隔」選項、韌體可在「時段間隔」選項和「排程時間間隔」選項之間選擇、方法是選取兩個選項的最低值。韌體會將1440除以您設定的「排定時間間隔」選項值、計算「排定時間間隔」選項的整數值。例如、1440/180 = 8。然後、韌體會將「timesPerDay」整數值與計算出的「排程間隔」整數值進行比較、並使用較小的值。

若要移除排程、請使用「刪除Volume」命令搭配「排程」參數。帶有「chschedule」參數的「刪除Volume」命令只會刪除排程、而不會刪除快照磁碟區。



== 最低韌體層級

7.83

7.86新增「排定日期」選項和「週期」選項。
