---
permalink: commands-a-z/diagnose-controller-iscsihostport.html 
sidebar: sidebar 
keywords: diagnose, controller, hostport, command, diagnostic, tests, copper, cable, host, interface, cards, support, roles 
summary: 診斷控制器iscsiHostPort命令會對iSCSI主機介面卡與控制器之間的銅線執行診斷測試。 
---
= 診斷控制器iSCSI主機纜線
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「診斷控制器iscsiHostPort」命令會對iSCSI主機介面卡與控制器之間的銅線執行診斷測試。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

您可以在選定的連接埠或所有連接埠上執行診斷。連接埠必須能夠支援纜線診斷。如果連接埠不支援纜線診斷、則會傳回錯誤訊息。



== 語法

[source, cli]
----
diagnose controller [(a|b)]
iscsiHostPort ([all] | [portLabel])
testID=cableDiagnostics
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
"控制器"
 a| 
您要執行纜線診斷測試的控制器。有效的控制器識別碼為「a」或「b」、其中「a」是插槽A中的控制器、而「b」是插槽B中的控制器將控制器識別碼括在方括弧（[]）內。如果未指定控制器、儲存管理軟體會傳回語法錯誤。



 a| 
「iscsiHostPort」
 a| 
您要在其中執行診斷測試的iSCSI主機連接埠。您可以在所有iSCSI主機連接埠上執行診斷、也可以在特定iSCSI主機連接埠上執行診斷。

如需詳細資訊、請參閱下列內容：

<<識別iSCSI主機連接埠標籤,"識別iSCSI主機連接埠標籤">>



 a| 
《testID》
 a| 
您要執行之診斷測試的識別碼。對於此診斷測試、唯一的選擇是「纜線診斷」。

|===


== 識別iSCSI主機連接埠標籤

您必須指定主機連接埠的標籤。請依照下列步驟指定主機連接埠標籤：

. 如果您不知道iSCSI主機連接埠的連接埠標籤、請執行「show controller」命令。
. 在結果的「主機介面」區段中、找出您要選取的主機連接埠。
+
[NOTE]
====
連接埠標籤是傳回「Port（連接埠）」欄位的完整值。

====
. 將連接埠標籤的整個值括在引號和方括弧中：["portlabel"。例如、如果連接埠標籤為「CH 2」、請如下指定iSCSI主機連接埠：
+
[listing]
----
iscsiHostPort[\"ch 2\"]
----
+
[NOTE]
====
如果您使用的是Windows命令列、且標籤包含管路（|）、則該字元應轉義（使用｛caret｝）；否則、該字元將會解譯為命令。例如、如果連接埠標籤為「e0b-0b」、請如下指定iSCSI主機連接埠：

====
+
[listing]
----
iscsiHostPort[\"e0b^|0b\"]
----


[NOTE]
====
為了提供向下相容性、以大括弧[]括住的iscsiPortNumber（而非引號和大括弧["]）仍可用於E2700、E5600或EF560控制器（以及其他前幾代E系列或EF系列控制器）。對於這些控制器、iscsiPortNumber的有效值如下：

* 對於具有整合式主機連接埠的控制器、編號為3、4、5或6。
* 如果控制器的主機連接埠僅在主機介面卡上、則編號為1、2、3或4。


先前的語法範例如下：

[listing]
----
iscsiHostPort[3]
----
====


== 附註

執行纜線診斷測試時、韌體會傳回下列資訊：

* *主機連接埠*：執行診斷測試的連接埠。
* * HIC*：與此連接埠相關聯的主機介面卡。
* 執行測試的日期和時間。
* *狀態*：
+
** *確定*：所有的纜線配對都很好、沒有任何故障。
** *開放式*：四對纜線中的一或多對纜線已開啟。
** *短*：四對纜線中的一或多對纜線發生短線。
** *不完整*：四對中的一或多對傳回不完整或無效的測試結果。


* *長度*：纜線長度以公尺為單位列出、並傳回下列纜線相關資訊：
+
** 當纜線狀態為「OK（正常）」時、會傳回纜線配對的大致長度。纜線配對的長度會顯示為範圍（L1-L2）、這是纜線配對的最短長度和最長長度。
** 如果纜線狀態為「Open（開啟）」或「Short（短）」、則為纜線配對中故障的大致距離。如果有一個故障、則會報告該纜線配對的長度。如果有多個故障、傳回的資訊會是故障的最短和最長長度。長度列示為L1<L2的範圍（L1-L2）。
** 如果纜線狀態不完整、傳回的資訊是韌體可成功測試的最短和最長纜線配對長度。有效纜線配對的長度列示為L1<L2範圍。


* 登錄纜線診斷暫存器的值。這些值採用十六進位格式：
+
** 兩個位元組顯示組合纜線狀態（每個連接埠四個位元）。
** 四個雙位元組數字顯示每個通道的長度。






== 最低韌體層級

7.77

8.10修改iSCSI主機連接埠的編號系統。
