---
permalink: commands-a-z/download-drive-firmware.html 
sidebar: sidebar 
keywords: download, drive, firmware, array, support, role, context, level 
summary: 下載磁碟機韌體命令會將韌體映像下載至磁碟機。 
---
= 下載磁碟機韌體 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
'Downloading drive韌體'命令會將韌體映像下載到磁碟機。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有 Storage Admin 或 Support Admin 角色。



== 背景

[CAUTION]
====
*可能會損壞儲存陣列組態*-若不正確下載磁碟機韌體、可能會導致磁碟機受損或資料存取中斷。

====
[NOTE]
====
「content」參數已過時。請改用「韌體」參數。

====
此命令一次只能將韌體映像下載至一個磁碟機型。如果您在指令碼中使用此命令、請確定只使用此命令一次。如果您多次使用此命令、作業可能會失敗。您可以使用「download storageArray driveFirmware'命令、一次將韌體映像下載到儲存陣列中的所有磁碟機。



== 語法

[source, cli, subs="+macros"]
----
download (drive [trayID,[drawerID,]slotID] | drives [trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn])
[online|offline] firmware file="filename"
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
「Dive」或「Drives」
 a| 
對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800和E5700控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。



 a| 
「線上」或「離線」
 a| 
選取「online（線上）」以執行線上磁碟機韌體下載、否則請選取「offline（離線）」。預設值為「離線」。



 a| 
檔案
 a| 
包含韌體映像之檔案的檔案路徑和檔案名稱。將韌體映像的檔案路徑和檔名括在雙引號（""）內。例如：

「file="C:\Program Files\CLI/dnld\drvfrm.dlp」

有效的檔案名稱副檔名為「.dlp」。



 a| 
韌體
 a| 
表示要下載控制器韌體。

|===


== 附註

在嘗試下載磁碟機韌體之前、請先採取下列預防措施：

* 除非您使用「online（線上）」參數、否則在下載韌體映像之前、請先停止儲存陣列的所有I/O活動。不含「online」參數的「download drive factivity」命令會封鎖所有I/O活動、直到下載完成或失敗為止；不過、為了預防、請務必停止可能影響磁碟機的所有I/O活動。
* 確定韌體映像檔與磁碟機匣相容如果您下載的韌體映像檔與您選取的磁碟機匣不相容、則磁碟機匣可能無法使用。
* 下載磁碟機韌體時、請勿對儲存陣列進行任何組態變更。嘗試變更組態可能會導致韌體下載失敗、並使選取的磁碟機無法使用。
* 對於使用此命令發出的線上磁碟機韌體更新要求、控制器會從下載新韌體的磁碟機清單中移除RAID 0磁碟區群組磁碟機。個別磁碟機的退貨狀態會設為「Never attempted with reReason（從未嘗試原因）」。


當您將韌體下載至磁碟機時、必須為儲存在系統上的韌體映像提供完整路徑和檔案名稱。

在儲存陣列的所有磁碟機上安裝韌體之前、您可以使用「下載磁碟機」命令來測試一個磁碟機上的韌體。下載會傳回下列其中一種狀態：

* 成功
* 不成功、原因不明
* 從未嘗試過、但有理由


"driv"參數同時支援大容量磁碟機匣和低容量磁碟機匣。大容量磁碟機匣具有可容納磁碟機的抽屜。從磁碟機匣中滑出抽取器、以便存取磁碟機。低容量磁碟機匣沒有抽屜。對於大容量磁碟機匣、您必須指定磁碟機匣的識別碼（ID）、匣的識別碼、以及磁碟機所在插槽的識別碼。對於低容量磁碟機匣、您只需要指定磁碟機匣的ID、以及磁碟機所在插槽的ID。對於低容量磁碟機匣、識別磁碟機位置的另一種方法是指定磁碟機匣的ID、將抽取匣的ID設為「0」、然後指定磁碟機所在插槽的ID。



== 最低韌體層級

7.60新增「drawerID」使用者輸入。

8.25新增「online」參數。
