---
permalink: commands-a-z/recover-volume.html 
sidebar: sidebar 
keywords: recover, raid, volume 
summary: 「recoverVolume」命令會建立具有指定內容的RAID Volume、而不會初始化磁碟機上的任何使用者資料區域。 
---
= 恢復 RAID 磁碟區 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「主機蓋磁碟區」命令會建立具有指定內容的RAID磁碟區、而不會初始化磁碟機上的任何使用者資料區域。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

參數值取自儲存陣列的恢復設定檔資料檔（「恢復設定檔」）。您可以在現有的Volume群組中建立恢復磁碟區、或使用此命令建立新的Volume群組。

[NOTE]
====
您只能從命令列執行此命令。您無法從GUI指令碼編輯器執行此命令。您無法使用儲存管理GUI來恢復磁碟區。

====
[NOTE]
====
您無法將此命令用於動態磁碟集區（DDP）磁碟區。

====


== 語法

[source, cli, subs="+macros"]
----
recover volume (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_])) |
(drives=pass:quotes[_trayID1_,pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn,_]pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])) |
volumeGroup=pass:quotes[_volumeGroupName_]))
[newVolumeGroup=pass:quotes[_volumeGroupName_]]
userLabel=pass:quotes["_volumeName_" volumeWWN="_volumeWWN_"
capacity=_volumeCapacity_
offset=_offsetValue_
raidLevel=(0 | 1 | 3 | 5 | 6)
segmentSize=_segmentSizeValue_
dssPreAllocate=(TRUE | FALSE)
SSID=_subsystemVolumeID_]
[owner=(a|b)]
[cacheReadPrefetch=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
[hostUnmapEnabled=(TRUE | FALSE)]
[blockSize=blockSizeValue]
----


== 參數

|===
| 參數 | 說明 


 a| 
「Dive」或「Drives」
 a| 
您要指派給磁碟區群組的磁碟機、其中包含您要恢復的磁碟區。對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800和E5700控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。



 a| 
「Volume Group」
 a| 
要在其中建立Volume的現有Volume群組名稱。（若要判斷儲存陣列中磁碟區群組的名稱、請執行「show storageArray profile」命令。）



 a| 
「newVolume Group」
 a| 
您要為新的Volume群組命名的名稱。將新的Volume群組名稱括在雙引號（""）內。



 a| 
「userLabel」
 a| 
您要恢復的Volume名稱。使用者標籤分為兩部分：

* Volume名稱。將磁碟區名稱括在雙引號（""）內。
* 全世界的Volume名稱「volumeWWN」、格式為16位元組識別碼、例如60080E500017B4320000000049887D77。將識別碼括在雙引號（""）內。


您必須輸入Volume的Volume名稱和全世界的Volume名稱。您必須先輸入磁碟區名稱。例如：

[listing]
----
userLabel="engdata"
volumeWWN=60080E500017B4320000000049887D77
----


 a| 
容量
 a| 
您要新增至儲存陣列的磁碟區大小。大小的定義單位為「位元組」、「KB」、「MB」、「GB」或「TB」。



 a| 
"偏移量"
 a| 
從磁碟區群組開頭到參照磁碟區開頭的區塊數。



 a| 
《raidLevel》
 a| 
包含磁碟機之磁碟區群組的RAID層級。有效值包括「0」、「1」、「3」、「5」或「6」。



 a| 
'大小'
 a| 
控制器在磁碟區群組中的單一磁碟機上寫入資料的資料量（以KB為單位）、然後再將資料寫入下一個磁碟機。有效值包括"8"、"16"、"32"、"64"、"128"、 "256"或"512"。



 a| 
「DssPreAllocate」
 a| 
此設定可開啟或關閉分配Volume儲存容量、以供未來區段大小變更之用。若要開啟分配、請將此參數設為「true」。若要關閉分配、請將此參數設為「假」。



 a| 
《SID》
 a| 
Volume的儲存陣列子系統識別碼。使用「show volume」命令來判斷儲存陣列子系統的識別碼。



 a| 
"老闆"
 a| 
擁有該磁碟區的控制器。有效的控制器識別碼為「a」或「b」、其中「a」是插槽A中的控制器、而「b」是插槽B中的控制器如果您未指定擁有者、則控制器韌體會決定擁有者。



 a| 
「cacheReadPrefetch」
 a| 
開啟或關閉快取讀取預先擷取的設定。若要關閉快取讀取預先擷取、請將此參數設為「假」。若要開啟快取讀取預先擷取、請將此參數設為「true」。



 a| 
「hostUnmapEnabled」
 a| 
當此參數設定為「True」時、主機就能發出UNMAP命令到Volume。只有資源配置的磁碟區才允許使用取消對應命令。



 a| 
「區塊大小」
 a| 
此設定是以位元組為單位的Volume區塊大小。

|===


== 附註

儲存管理軟體會收集受監控儲存陣列的還原設定檔、並將設定檔儲存在儲存管理站上。

"driv"參數同時支援大容量磁碟機匣和低容量磁碟機匣。大容量磁碟機匣具有可容納磁碟機的抽屜。從磁碟機匣中滑出抽取器、以便存取磁碟機。低容量磁碟機匣沒有抽屜。對於大容量磁碟機匣、您必須指定磁碟機匣的識別碼（ID）、匣的識別碼、以及磁碟機所在插槽的識別碼。對於低容量磁碟機匣、您只需要指定磁碟機匣的ID、以及磁碟機所在插槽的ID。對於低容量磁碟機匣、識別磁碟機位置的另一種方法是指定磁碟機匣的ID、將抽取匣的ID設為「0」、然後指定磁碟機所在插槽的ID。

如果您嘗試使用「drive」參數或「drives」參數來恢復磁碟區、而且磁碟機處於未指派狀態、則控制器會自動建立新的磁碟區群組。使用「newVolume Group」參數來指定新Volume群組的名稱。

您可以使用字母數字字元、底線（_）、連字號（-）和井號（#）的任意組合來命名。名稱最多可包含30個字元。

「擁有者」參數可定義擁有該磁碟區的控制器。磁碟區的慣用控制器擁有權是目前擁有該磁碟區群組的控制器。



== 預先配置儲存容量

「dssPreAllocate」參數可讓您在磁碟區中指派容量、以儲存用於重建磁碟區的資訊。當您將「dssPreallocate」參數設定為「true」時、控制器韌體中的儲存空間分配邏輯會預先配置磁碟區中的空間、以供未來的區段大小變更。預先配置的空間是允許的最大區段大小。要正確恢復無法從控制器資料庫擷取的磁碟區組態、必須使用「dssPreAllocate」參數。若要關閉預先分配功能、請將「dssPreAllocate」設為「假」。



== 區段大小

區段大小決定控制器在磁碟區中的單一磁碟機上寫入多少資料區塊、然後再將資料寫入下一個磁碟機。每個資料區塊儲存512個位元組的資料。資料區塊是最小的儲存單位。區段的大小決定其包含多少資料區塊。例如、8-KB區段可容納16個資料區塊。64 KB區段可容納128個資料區塊。

當您輸入區段大小的值時、會對照控制器在執行時間提供的支援值來檢查該值。如果您輸入的值無效、控制器會傳回有效值清單。使用單一磁碟機進行單一要求時、其他磁碟機仍可同時處理其他要求。

如果磁碟區位於單一使用者正在傳輸大量資料（例如多媒體）的環境中、則當單一資料傳輸要求以單一資料等量磁碟區來處理時、效能就會達到最大化。（資料等量磁碟區是區段大小乘以磁碟區群組中用於資料傳輸的磁碟機數量。） 在此情況下、多個磁碟機用於相同的要求、但每個磁碟機只能存取一次。

若要在多使用者資料庫或檔案系統儲存環境中達到最佳效能、請設定區段大小、將滿足資料傳輸要求所需的磁碟機數量降至最低。



== 快取讀取預先擷取

快取讀取預先擷取可讓控制器在控制器讀取主機要求的資料區塊並將其從磁碟複製到快取時、將其他資料區塊複製到快取中。此動作可增加日後從快取執行資料要求的機會。對於使用循序資料傳輸的多媒體應用程式而言、快取讀取預先擷取非常重要。您使用的儲存陣列組態設定、會決定控制器讀取到快取的其他資料區塊數目。「cacheReadPrefetch」參數的有效值為「true」或「假」。



== 最低韌體層級

5.43

7.10新增RAID 6層級功能和「newVolume Group」參數。

7.60新增「drawerID」使用者輸入。

7.75新增了「data Assurance」參數。

8.78新增了「hostUnmapEnabled」參數。

11.70.1會新增「區塊大小」參數。
