---
permalink: commands-a-z/recover-sasport-miswire.html 
sidebar: sidebar 
keywords: recover, sas, port, mis-wire 
summary: recovering sasPort miswire命令會告知控制器已採取修正行動、從錯誤的線路狀況中恢復。 
---
= 恢復SAS連接埠連線錯誤
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"走 線錯誤"命令告訴控制器已採取修正行動、從錯誤的線路狀況中恢復。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有 Storage Admin 或 Support Admin 角色。



== 背景

然後、控制器可以重新啟用任何因為偵測到連線錯誤而停用的SAS連接埠。修正任何SAS連線錯誤的情況後、請執行此命令。

SAS有線錯誤狀況可能是下列其中一項：

* 無效的SAS拓撲
* 控制器主機連接埠至擴充匣連線
* 啟動器至磁碟機拓撲連線
* ESM-接線錯誤




== 語法

[source, cli]
----
recover sasPort miswire
----


== 參數

無。



== 附註

偵測到線路錯誤時、控制器韌體會報告下列資訊：

* 表示發生配線錯誤狀況的重要MEL事件
* 「需要注意」的情況
* 表示連線錯誤的恢復動作


此外、控制器會針對磁碟機、ESMS及磁碟匣報告「冗餘遺失」資訊、這些磁碟機、ESMS及磁碟匣因為連線錯誤而只有一個存取路徑（例如儲存陣列中的底部兩個磁碟匣）。備援遺失資訊並非SAS拓撲的唯一資訊。

以下是與SAS連接埠連線錯誤相關的事件通知：

* 偵測到SAS連線錯誤
* HBA已連線至磁碟機通道
* 跨有線磁碟機通道


對於控制器停用一或多個SAS連接埠以保護SAS網域完整性的線上錯誤情況、請採取下列步驟、從情況中恢復：

. 確定哪個纜線位於錯誤位置、然後將其拔下。如果最後一項行動是安裝新的纜線、這是最可能的選擇。如果沒有、請尋找連接至非儲存陣列一部分的裝置的纜線、或是連接至通道之間的纜線。恢復事件應報告偵測到錯誤線路的通道、以及可能的匣
. 拔下纜線或將纜線移至正確位置後、請執行「機箱蓋sasPort miswire」命令。控制器會嘗試重新啟用偵測到連線錯誤時停用的任何SAS連接埠。
. 如果您移除或移動的纜線已修正錯誤的配線、但控制器只能存取停用的連接埠、則控制器將無法重新啟用已停用的SAS連接埠。若要完成恢復、您必須重新啟動儲存陣列中的磁碟匣。




== 最低韌體層級

8.10.
