---
permalink: commands-a-z/recopy-volumecopy-target.html 
sidebar: sidebar 
keywords: volumecopy, target, command, operation, volume, copy, pair, reinitiate, array, role, context 
summary: Recopy volumeCopy target命令會使用現有的Volume複製配對、重新啟動Volume複製作業。 
---
= 重新複製Volume複本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「recopy volumeCopy target」命令會使用現有的Volume複製配對、重新啟動Volume複製作業。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

[NOTE]
====
在韌體版本7.83中、不再使用「copyType=（online | offline）」參數。

====
此命令適用於快照映像磁碟區複本配對。

此命令可搭配使用快照映像磁碟區所建立的磁碟區複本配對使用。

[NOTE]
====
啟動Volume複製作業會覆寫目標磁碟區上的所有現有資料、將目標磁碟區設為主機唯讀、並使與目標磁碟區相關的所有快照映像磁碟區（若有）失效。如果您之前曾經將目標磁碟區當作複本、請確定您不再需要資料或已備份資料。

====


== 語法

[source, cli]
----
recopy volumeCopy target [targetName]
[source [sourceName]]
[copyPriority=(highest | high | medium | low | lowest)]
[targetReadOnlyEnabled=(TRUE | FALSE)]
----


== 參數

|===
| 參數 | 說明 


 a| 
《目標》
 a| 
您要重新啟動Volume複製作業的目標Volume名稱。將目標Volume名稱括在方括弧（[]）內。如果目標Volume名稱包含特殊字元、則必須在方括弧內以雙引號（""）括住目標Volume名稱。



 a| 
《來源》
 a| 
您要重新啟動Volume複製作業的來源Volume名稱。將來源Volume名稱括在方括弧（[]）內。如果來源Volume名稱包含特殊字元、則必須在方括弧內以雙引號（""）括住來源Volume名稱。



 a| 
「copyPriority」
 a| 
Volume複本相對於主機I/O活動的優先順序。有效值包括「最高」、「高」、「中等」、「低」或「最低」。



 a| 
"targetReadOnlyEnabled"
 a| 
此設定可讓您寫入目標磁碟區、或僅從目標磁碟區讀取。若要寫入目標Volume、請將此參數設為「假」。若要防止寫入目標Volume、請將此參數設為「true」。

|===


== 附註

複製優先順序定義用於在來源Volume與Volume複製配對的目標Volume之間複製資料的系統資源量。如果您選取最高優先順序層級、則Volume複本會使用最多的系統資源來執行Volume複本、進而降低主機資料傳輸的效能。



== 最低韌體層級

6.10.

7.83移除「copyType=（online | offline）」參數。
