---
permalink: commands-a-z/reduce-disk-pool-capacity.html 
sidebar: sidebar 
keywords: reduce, disk pool, capacity 
summary: set diskPool命令會從資源池邏輯移除磁碟機、藉此減少磁碟資源池的容量。 
---
= 減少磁碟集區容量
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「show pool」命令可從資源池邏輯移除磁碟機、藉此減少磁碟資源池的容量。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800、E5700、 EF600和EF300陣列、只要安裝所有SMcli套件即可。



== 角色

若要在E2800、E5700、EF600或EF300儲存陣列上執行此命令、您必須具有儲存管理員角色。



== 背景

此命令使用動態容量減量（DCR）功能、可讓您從磁碟集區移除選取的磁碟機、並視需要重新使用移除的磁碟機。

在單一簽帳卡讀取器作業中、可從磁碟集區移除的磁碟機數量上限為60個。您無法將磁碟集區減少至低於最小磁碟集區大小。



== 語法

[listing, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
removeDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1
... trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_])
----


== 參數

|===
| 參數 | 說明 


 a| 
《DiskPool》
 a| 
您要減少容量的磁碟集區名稱。將磁碟集區名稱括在方括弧中（[]）。



 a| 
《實作磁碟機》
 a| 
對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800和E5700控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。

|===


== 附註

每個磁碟集區名稱都必須是唯一的。您可以使用任何字母數字字元、底線（_）、連字號（-）和井號（#）的組合作為使用者標籤。使用者標籤最多可有30個字元。

如果您需要建立個別群組或從儲存陣列移除不需要的容量、可能需要從磁碟集區移除所選的磁碟機。移除的磁碟機會變成未指派的磁碟機、而其上的資料會重新分配到磁碟集區中的其餘磁碟機。磁碟集區的容量會因您移除的磁碟機容量而減少。從磁碟集區移除磁碟機一律會做為背景工作、而且在此作業期間、磁碟區仍可完全存取。移除作業的進度會報告為長時間執行作業狀態的一部分。

如果保留在磁碟集區中的磁碟機沒有足夠的可用容量、無法儲存您從磁碟集區移除之磁碟機上的所有資料、則此命令會失敗。磁碟集區中的保留容量可用來儲存您從磁碟集區移除之磁碟機上的資料。但是、如果保留容量低於臨界臨界值、則會將重大事件寫入主要事件記錄。

減少磁碟集區大小可能會導致所需的保留容量變小。在某些情況下、為了降低此命令失敗的可能性、請在執行此命令之前先減少保留容量、以增加磁碟集區資料的可用空間量。

控制器韌體會決定您可以移除多少個磁碟機、然後選取要移除的特定磁碟機。控制器韌體會根據在剩餘磁碟機上重新分配資料所需的可用空間量來計算、而不會耗用任何保留用於重建的容量。如果磁碟集區的可用容量已低於保留的重建磁碟機容量、則控制器不允許開始執行簽帳卡讀取器作業。

簽帳卡讀取器作業可能導致設定的容量超過一個或兩個資源池使用率臨界值。如果是、則會發出正常臨界值警示。



== 最低韌體層級

8.10.
