---
permalink: commands-a-z/reset-drive.html 
sidebar: sidebar 
keywords: reset, drive 
summary: 重設磁碟機命令會重新啟動磁碟區群組或磁碟集區中的磁碟機、以協助恢復出現不一致或非最佳行為的磁碟機。 
---
= 重置驅動器 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「重新設定磁碟機」命令會將磁碟機重新啟動至磁碟區群組或磁碟集區、以協助恢復出現不一致或非最佳行為的磁碟機。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

只要將磁碟機重新開機、就能清除導致不一致或非最佳行為的錯誤。如此可避免在磁碟機僅發生暫時性、非致命的錯誤時更換磁碟機、而且磁碟機仍可繼續運作。以這種方式重設磁碟機可減少中斷、並避免更換磁碟機。

如果無法透過重新啟動磁碟機來修正問題、資料會從磁碟機複製、磁碟機將會關機以供更換。

[NOTE]
====
此命令無法用於由Pl大膽 製造的SSD磁碟機。使用「show storageArray profile」命令或「show drive'命令」來顯示磁碟機的製造商。

====


== 語法

[source, cli]
----
reset drive([trayID,[drawerID,]slotID] | <"wwID">)
----


== 參數

|===
| 參數 | 說明 


 a| 
"大"
 a| 
對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800和E5700控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。



 a| 
"大"
 a| 
您要更換之磁碟機的全球識別碼（WWID）。將WWID以雙引號（""）括在角括弧（<>）內。

|===


== 附註

"driv"參數同時支援大容量磁碟機匣和低容量磁碟機匣。大容量磁碟機匣具有可容納磁碟機的抽屜。從磁碟機匣中滑出抽取器、以便存取磁碟機。低容量磁碟機匣沒有抽屜。對於大容量磁碟機匣、您必須指定磁碟機匣的識別碼（ID）、匣的識別碼、以及磁碟機所在插槽的識別碼。對於低容量磁碟機匣、您只需要指定磁碟機匣的ID、以及磁碟機所在插槽的ID。對於低容量磁碟機匣、識別磁碟機位置的另一種方法是指定磁碟機匣的ID、將抽取匣的ID設為「0」、然後指定磁碟機所在插槽的ID。

重新啟動磁碟機之後、控制器必須先確認磁碟機是否正常運作、才能重新使用。如果磁碟機無法驗證、則會標示為故障磁碟機。關機後再開機故障磁碟機需要全域熱備援磁碟機、並在其投入使用後、將完整複本複製回更換磁碟機。

故障磁碟機無法在24小時內重設一次以上的電源循環、在某些情況下無法重設一次以上。磁碟機電源週期的臨界值和計數器會保留在持續儲存設備中、並包含在狀態擷取資料中。當磁碟機重新開機時、會記錄資訊事件。



== 最低韌體層級

8.20
