---
permalink: commands-a-z/save-storagearray-arvmstats-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: save, asynchronous, mirror, group, statistics 
summary: SAVE storageArray arvmStats asyncdMirrorGroup命令會將同步統計資料儲存至非同步鏡射鏡射群組中一或多個成員磁碟區的檔案。 
---
= 儲存非同步鏡射群組統計資料
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「儲存陣列arvmStats asyncdMirrorGroup」命令會將同步統計資料儲存至非同步鏡像群組中一或多個成員磁碟區的檔案。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800及E5700陣列、 只要安裝所有SMcli套件、



== 角色

若要在E2800或E5700儲存陣列上執行此命令、您必須擁有儲存管理員角色。



== 背景

所收集的統計資料僅適用於本機儲存陣列上主要角色的非同步鏡射鏡射群組成員磁碟區。

在同步處理程序期間會收集一組資料、用以評估鏡射組態的運作狀況。資料會以一組_samples_的形式收集。在同步處理程序開始時會建立一個範例、並在同步處理程序開始時定期更新。

範例會收集資料、直到同步處理程序完成或同步處理程序中斷為止、例如磁碟區所有權傳輸或「讀寫」錯誤。當同步處理程序中斷解決時（例如、磁碟區會傳輸至替代控制器）、系統會在同步處理程序繼續時建立並更新新的範例。



== 語法

[listing, subs="+macros"]
----
save storageArray arvmStats asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
arvmStats file=pass:quotes["_filename_"]
"
[volume=pass:quotes["_volumeName_"]]
[sampleType=(all | mostRecent | longestSyncTime | errors)]
[recordLimit=(1-90)]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
《非yncdMirrorGroup》（英文）
 a| 
儲存同步統計資料的非同步鏡射群組名稱。將非同步鏡射群組名稱括在方括弧（[]）內。如果非同步鏡射群組名稱包含特殊字元或數字、則必須將非同步鏡射群組名稱以雙引號（""）括在方括弧內。



 a| 
檔案
 a| 
您要儲存同步處理統計資料的檔案路徑和檔案名稱。將檔案名稱括在雙引號（""）內。例如：

「file="C:\Program Files\CLI/logs\asynchdata.csv"」

此命令不會自動將副檔名附加至儲存的檔案。您可以使用任何檔案名稱、但必須使用「.csv"副檔名。



 a| 
《Volume》（Volume）
 a| 
此參數為選用項目。擷取同步統計資料之非同步鏡射群組中的特定成員磁碟區名稱。如果未指定Volume、則會儲存非同步鏡射鏡射群組中每個成員磁碟區的統計資料。

如果在非同步鏡射群組中收集多個磁碟區的統計資料、則所有資料都會寫入同一個檔案。

將磁碟區名稱括在雙引號（""）內。



 a| 
「取樣類型」
 a| 
此參數為選用項目。「最大取樣類型」的預設值為「ALL」。

* 「All（全部）」-所有三種樣本類型的資料都會收集並寫入同一個檔案中。
* 「最近50個重新同步樣本記錄統計資料」。
* 「longestSyncTime」-收集最近20個最長重新同步樣本的統計資料。
* 「錯誤」-記錄最近20個失敗的重新同步樣本的統計資料。這些範例包括故障代碼。




 a| 
「重複限制」
 a| 
此參數為選用項目。記錄限制的預設值為「無限制」。「重複限制」必須大於0且小於或等於90。

|===


== 附註

系統會擷取主要角色中鏡射磁碟區的統計資料。收集的統計資料包括下列資料：

* 同步開始時間
* 同步類型（手動或定期）
* 同步處理持續時間
* 傳送的位元組數
* 最長寫入時間（單一寫入）
* 最短寫入時間（單一寫入）
* 最低同步資料速率
* 最大同步資料速率
* 總寫入時間
* 儲存庫使用率（%）
* 恢復點時間


在初始同步期間、統計資料樣本大約每15分鐘擷取一次。

同步統計資料會包含在支援套裝組合中。



== 最低韌體層級

7.84
