---
permalink: commands-a-z/save-storagearray-warningevents.html 
sidebar: sidebar 
keywords: save, storage, array, events 
summary: SAVE storageArray warningEvent命令會將重大事件記錄中的事件儲存至檔案。 
---
= 保存儲存陣列事件 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「儲存陣列warningEvents」命令可將事件從主要事件記錄儲存至檔案。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

此命令會將事件從主要事件記錄儲存至檔案。您可以儲存下列事件：

* *重大事件*：儲存陣列發生錯誤、需要立即解決。如果您未立即修正錯誤、可能會遺失資料存取。
* *警告事件*：儲存陣列發生錯誤、導致效能降級或無法從其他錯誤中恢復。存取資料並未遺失、但您必須修正錯誤、以免在發生其他錯誤時遺失資料存取。
* *資訊事件*：儲存陣列上發生的事件、不會影響正常作業。此事件會報告組態或其他資訊的變更、可能有助於評估儲存陣列的效能表現。
* *偵錯事件*：儲存陣列上發生的事件、提供您可用來協助判斷導致錯誤的步驟或狀態的資訊。您可以將內含此資訊的檔案傳送給技術支援部門、以協助判斷錯誤原因。


[NOTE]
====
某些儲存陣列可能無法支援所有四種類型的事件。

====


== 語法

[source, cli, subs="+macros"]
----
save storageArray (allEvents | criticalEvents |
warningEvents | infoEvents | debugEvents)
file=pass:quotes["_filename_"]
[count=pass:quotes[_numberOfEvents_]]
[forceSave=(TRUE | FALSE)]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
「allEvents」
 a| 
將所有事件儲存至檔案的參數。



 a| 
「重大事件」
 a| 
僅將關鍵事件儲存至檔案的參數。



 a| 
《警告事件》
 a| 
僅將警告事件儲存至檔案的參數。



 a| 
「資訊活動」
 a| 
僅將資訊事件儲存至檔案的參數。



 a| 
《DebugEvents》
 a| 
僅將偵錯事件儲存至檔案的參數。



 a| 
檔案
 a| 
您要儲存事件的檔案路徑和檔案名稱。將檔案名稱括在雙引號（""）內。例如：

「file="C:\Program Files\CLI/logs\evations.txt"」

包含主要事件記錄內容的檔案預設名稱為「major事件記錄檔」。此命令不會自動將副檔名附加至儲存的檔案。輸入檔案名稱時、您必須指定副檔名。



 a| 
《數》
 a| 
您要儲存至檔案的事件數。如果您未輸入計數的值、則會將符合您指定事件類型的所有事件儲存至檔案。如果您輸入計數的值、則只會將該事件數（從上次輸入的事件開始算起）儲存至檔案。使用整數值。



 a| 
「forceSave」
 a| 
強制儲存偵錯事件的參數、您可能已從檢視篩選為檔案。若要強制儲存事件、請將此參數設為「true」。預設值為「假」。

[NOTE]
====
使用此參數可儲存SANtricity 已從「事件檢視器」中篩選出的偵錯事件。

====
|===


== 最低韌體層級

7.77新增下列參數：

* 《警告事件》
* 「資訊活動」
* 《DebugEvents》
* 「forceSave」

