---
permalink: commands-a-z/set-disk-pool-modify-disk-pool.html 
sidebar: sidebar 
keywords: set, disk pool, modify 
summary: set diskPool命令會將容量新增至磁碟集區（動態容量擴充或DCE）、或變更整個磁碟集區的控制器擁有權。 
---
= 設定磁碟集區（修改磁碟集區）
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「show diskPool」命令可將容量新增至磁碟集區（動態容量擴充或DCE）、或變更整個磁碟集區的控制器擁有權。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800、E5700、 EF600和EF300陣列、只要安裝所有SMcli套件即可。



== 角色

若要在E2800、E5700、EF600或EF300儲存陣列上執行此命令、您必須具有儲存管理員角色。



== 背景

這兩項作業是互不相容的。



== 語法

[listing, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
(addDrives=pass:quotes[[_trayID1_,_drawerID1_,_slotID1_ ... _trayIDn_,_drawerIDn_,_slotIDn_]] |
addCapacity=pass:quotes[(_diskPoolCapacity_))]
[owner=(a| b)]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
《DiskPool》
 a| 
您要修改的磁碟集區名稱。將磁碟集區名稱括在方括弧中（[]）。如果磁碟集區名稱包含特殊字元或僅包含數字、則必須在方括弧內以雙引號（""）括住名稱。



 a| 
《附加磁碟機》
 a| 
您要新增至磁碟集區的磁碟機。對於大容量磁碟機匣、請指定您要新增之磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定您要新增之磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。插槽ID值為1至24。將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。

[NOTE]
====
此功能的磁碟機限制為12個磁碟機。

====


 a| 
《addCapacity》
 a| 
您要新增至磁碟集區的額外儲存容量量。此參數會自動選取磁碟機以符合您要新增的容量。容量的定義單位為「位元組」、「KB」、「MB」、「GB」或「TB」。



 a| 
"老闆"
 a| 
擁有磁碟集區的控制器。有效的控制器識別碼為「a」或「b」、其中「a」是插槽A中的控制器、而「b」是插槽B中的控制器如果您未指定擁有者、則控制器韌體會決定擁有者。

|===


== 附註

在新增磁碟機時、磁碟集區中已存在的磁碟區仍會保持連線、可供I/O作業使用。新增容量之前、磁碟集區必須處於完整狀態。如果磁碟集區未處於完整狀態、請在新增磁碟機之前、先執行「設磁碟完整」命令。

若要新增容量、請使用「addDrives」參數指定個別磁碟機、或使用「addCapacity」參數指定磁碟機容量。如果您使用「addDrives」、主機必須先驗證磁碟機集、才能執行作業。如果您使用「addCapacity」參數、您指定的容量會被視為要新增的最小容量。候選磁碟機的服務品質與容量最相符、大於或等於您所指定的容量。如果沒有符合最低要求的候選磁碟機、或指定的磁碟機清單無法使用、或偵測到屬性不相符、則作業會失敗。

您也可以使用此命令、將磁碟集區的擁有權從儲存陣列中的一個控制器變更為另一個控制器。使用此命令變更擁有權與使用命令新增磁碟機或新增容量是互不相容的。



== 最低韌體層級

7.83
