---
permalink: commands-a-z/set-host.html 
sidebar: sidebar 
keywords: set, host 
summary: set host命令會將主機指派給主機群組、或將主機移至其他主機群組。 
---
= 設定主機 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「show host」命令可將主機指派給主機群組、或將主機移至其他主機群組。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

您也可以建立新的主機群組、然後使用此命令將主機指派給新的主機群組。此命令執行的動作取決於主機是否具有個別對應或沒有個別對應。



== 語法

[source, cli, subs="+macros"]
----
set host [hostName]
hostGroup=pass:quotes[("_hostGroupName_"] | none | defaultGroup)
userLabel=pass:quotes["_newHostName_"]
hostType=pass:quotes[(_hostTypeIndexLabel_ | _hostTypeIndexNumber_)]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
"主機"
 a| 
要指派給主機群組的主機名稱。將主機名稱括在方括弧中（[]）。如果主機名稱包含特殊字元或數字、則必須在方括弧內以雙引號（""）括住主機名稱。



 a| 
「主機群組」
 a| 
要指派主機的主機群組名稱。（下表定義當主機有或沒有個別對應時、命令的執行方式。） 將主機群組名稱括在雙引號（""）內。「資料管理群組」選項是包含磁碟區對應主機的主機群組。



 a| 
「userLabel」
 a| 
新的主機名稱。將主機名稱括在雙引號（""）內。



 a| 
「hostType」
 a| 
主機連接埠的主機類型索引標籤或編號。使用「show storageArray hostTypeTable」命令來產生可用的主機類型識別碼清單。如果主機類型有特殊字元、請將主機類型括在雙引號（""）內。

|===
[cols="3*"]
|===
| 主機群組參數 | 主機具有個別對應 | 主機沒有個別對應 


 a| 
hostGroupName_
 a| 
主機會從目前的主機群組中移除、並置於由「_hostGroupName_」定義的新主機群組之下。
 a| 
主機會從目前的主機群組中移除、並置於由「_hostGroupName_」定義的新主機群組之下。



 a| 
無
 a| 
主機會從主機群組中移除為獨立的分割區、並放置在根節點下。
 a| 
主機會從目前的主機群組中移除、並置於預設群組之下。



 a| 
「資料錯誤群組」
 a| 
命令失敗。
 a| 
主機會從目前的主機群組中移除、並置於預設群組之下。

|===


== 附註

使用此命令時、您可以指定一或多個選用參數。

對於名稱、您可以使用字母數字字元、連字號和底線的任意組合。名稱最多可包含30個字元。



== 最低韌體層級

6.10.
