---
permalink: commands-a-z/set-drive-nativestate.html 
sidebar: sidebar 
keywords: set, foreign, drive, native 
summary: set磁碟機nativeState命令會將遺失的（外部）磁碟機新增回原始磁碟區群組、並將其納入新儲存陣列的磁碟區群組。 
---
= 將外部磁碟機設定為原生磁碟機
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「show drive nativeState」命令會將遺失的（外部）磁碟機新增回原始磁碟區群組、並將其納入新儲存陣列的磁碟區群組。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800、E5700、 EF600和EF300陣列、只要安裝所有SMcli套件即可。



== 角色

若要在E2800、E5700、EF600或EF300儲存陣列上執行此命令、您必須具有儲存管理員角色。



== 背景

當磁碟機是儲存陣列中磁碟區群組的一部分時、即視為原生磁碟機。如果磁碟機不屬於儲存陣列中的磁碟區群組、或無法與傳輸至新儲存陣列的磁碟區群組磁碟機一起匯入、則該磁碟機被視為外部磁碟機。後者的故障會在新的儲存陣列上建立不完整的磁碟區群組。

此作業僅用於緊急恢復：當一個或多個磁碟機需要從外部磁碟機狀態變更、並在其原始磁碟區群組中恢復為原生狀態時。

[NOTE]
====
*可能的資料毀損或資料遺失*-使用此命令的原因並非先前所述的原因、可能導致資料遺失而不另行通知。

====


== 語法

[listing, subs="+macros"]
----
set (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_)] | drives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)] |
allDrives) nativeState
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
「Dive」或「Drives」
 a| 
對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800、E5700、EF600和EF300控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。



 a| 
"allDrives"
 a| 
用於選擇所有磁碟機的設定。

|===


== 附註

"driv"參數同時支援大容量磁碟機匣和低容量磁碟機匣。大容量磁碟機匣具有可容納磁碟機的抽屜。從磁碟機匣中滑出抽取器、以便存取磁碟機。低容量磁碟機匣沒有抽屜。對於大容量磁碟機匣、您必須指定磁碟機匣的識別碼（ID）、匣的識別碼、以及磁碟機所在插槽的識別碼。對於低容量磁碟機匣、您只需要指定磁碟機匣的ID、以及磁碟機所在插槽的ID。對於低容量磁碟機匣、識別磁碟機位置的另一種方法是指定磁碟機匣的ID、將抽取匣的ID設為「0」、然後指定磁碟機所在插槽的ID。



== 最低韌體層級

7.10.

7.60新增「drawerID」使用者輸入。
