---
permalink: commands-a-z/set-tray-drawer.html 
sidebar: sidebar 
keywords: set, drawer, service, action, allowed, indicator 
summary: 「Set tray t抽屜」命令會開啟或關閉裝有磁碟機的藥櫃上的「Service Action允許的服務動作」指示燈。 
---
= 設定允許藥櫃服務動作指示
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「設置匣抽屜」命令會在裝有磁碟機的抽屜上開啟或關閉「允許服務動作」指示燈。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800、E5700、 EF600和EF300陣列、只要安裝所有SMcli套件即可。



== 角色

若要在E2800、E5700、EF600或EF300儲存陣列上執行此命令、您必須具有儲存管理員角色。



== 背景

抽屜用於大容量磁碟機匣。從磁碟機匣中滑出抽取器、以便存取磁碟機。此命令僅適用於使用抽屜的磁碟機匣。如果儲存陣列不支援「允許服務動作」指示燈功能、此命令會傳回錯誤。如果儲存陣列支援該命令、但無法開啟或關閉指示燈、則此命令會傳回錯誤訊息。



== 語法

[listing, subs="+macros"]
----
set tray pass:quotes[[_trayID_]] drawer pass:quotes[[_drawerID_]]
serviceAllowedIndicator=(on | off | forceOnWarning)
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
"紙匣"
 a| 
藥櫃所在的匣。紙匣ID值為0至99。將紙匣ID值括在方括弧（[]）內。如果您未輸入紙匣ID值、控制器紙匣的紙匣ID為預設值。



 a| 
《道爾維爾》
 a| 
您要開啟或關閉「允許維修行動」指示燈的藥櫃位置。藥櫃ID值為1至5。將藥櫃ID值括在方括弧（[]）內。



 a| 
「服務指標」
 a| 
用於開啟或關閉「允許服務動作」指示燈的設定。若要開啟「允許維修操作」指示燈、請將此參數設為「開啟」。若要關閉「允許維修操作」指示燈、請將此參數設為「關閉」。

如需使用「forceOnWarning」的相關資訊、請參閱附註。

|===


== 附註

在輸入此命令之前、磁碟機匣必須符合下列條件：

* 磁碟機匣不能溫度過高。
* 風扇的狀態必須為「Optimal（最佳）」。
* 所有磁碟機匣元件都必須就位。
* 磁碟機匣中的磁碟區無法處於降級狀態。如果您從磁碟機匣中移除磁碟機、且磁碟區已處於降級狀態、則磁碟區可能會故障。


[NOTE]
====
如果您不符合上述任何條件、請勿發出此命令。

====
所有磁碟機位於受影響磁碟機匣的磁碟區都會被檢查、以確保磁碟區在傳送命令之前具有藥櫃遺失保護。如果磁碟區具有藥櫃遺失保護、則「允許設定服務動作」命令會繼續執行、而不會停止磁碟區的I/O活動。

如果受影響的藥櫃中有任何磁碟區沒有藥櫃遺失保護、您必須停止這些磁碟區的I/O活動。此時會出現一則警告、指出此命令不應完成。

若要開啟或關閉整個高容量磁碟機匣的「允許維修操作」指示燈、請使用「設置匣服務項目指示」命令。



== 使用forceOnWarning

如果您準備移除元件、並想要覆寫磁碟區沒有藥櫃遺失保護的警告、請輸入此參數：

[listing]
----
serviceAllowedIndicator=forceOnWarning
----
「forceOnWarning」參數會傳送要求、要求準備將元件移除至控制器韌體、並強制執行「設為藥櫃服務」指令。

[NOTE]
====
此參數會標記藥櫃中的所有磁碟機無法存取、並可能導致磁碟區故障和複雜的恢復、包括必須重新啟動主機。請謹慎使用此參數。

====


== 最低韌體層級

7.60
