---
permalink: commands-a-z/set-drive-securityid.html 
sidebar: sidebar 
keywords: set, fips, drive, security, identifier 
summary: Set磁碟機安全性ID命令用於將FIPS磁碟機重設回原始製造商設定。 
---
= 設定FIPS磁碟機安全性識別碼
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「設磁碟機安全性ID」命令可用來將FIPS磁碟機重設回原始製造商設定。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800、E5700、 EF600和EF300陣列、只要安裝所有SMcli套件即可。



== 角色

若要在E2800、E5700、EF600或EF300儲存陣列上執行此命令、您必須具有「安全性管理」角色。



== 背景

[NOTE]
====
此命令會將FIPS磁碟機重設回原始製造商設定、並清除所有現有的磁碟機資料。這項作業完全無法還原。如果磁碟機因為無效或遺失的安全金鑰檔案或未知的密碼、而被鎖定、則可能需要執行此動作。所有現有的磁碟機資料都會被清除。

====
若要清除FDE磁碟機、請使用「Start secureErase」命令。



== 語法

[listing, subs="+macros"]
----
set drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] securityID="string"
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
"大"
 a| 
對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800和E5700控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。



 a| 
"ecurityID"
 a| 
要清除磁碟機的安全性ID、以字串形式顯示。此字串最多可包含32個字元。安全ID的形式會因製造商而異。

[NOTE]
====
若要尋找安全ID、請移除磁碟機、並讀取磁碟機箱標籤上的安全ID。

====
|===


== 附註

"driv"參數同時支援大容量磁碟機匣和低容量磁碟機匣。大容量磁碟機匣具有可容納磁碟機的抽屜。從磁碟機匣中滑出抽取器、以便存取磁碟機。低容量磁碟機匣沒有抽屜。對於大容量磁碟機匣、您必須指定磁碟機匣的識別碼（ID）、匣的識別碼、以及磁碟機所在插槽的識別碼。對於低容量磁碟機匣、您只需要指定磁碟機匣的ID、以及磁碟機所在插槽的ID。對於低容量磁碟機匣、識別磁碟機位置的另一種方法是指定磁碟機匣的ID、將抽取匣的ID設為「0」、然後指定磁碟機所在插槽的ID。



== 範例

[listing]
----
set drive [1,31,4] securityID="V2zdvLTdGWdWyTALGHns";
----


== 最低韌體層級

8.25
