---
permalink: commands-a-z/set-disk-pool.html 
sidebar: sidebar 
keywords: set, disk pool 
summary: set diskPool命令會根據指定的參數、設定與磁碟集區相關的屬性。 
---
= 設定磁碟集區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「Set diskPool」命令會根據指定的參數、設定與磁碟集區相關的屬性。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 語法

[source, cli, subs="+macros"]
----
set (diskPool pass:quotes[[_diskPoolName_]] |
diskPools pass:quotes[[_diskPoolName1_ ... _diskPoolNameN_]] | allDiskPools)
[reservedDriveCount=pass:quotes[_reservedDriveCountValue_]]
[warningThreshold=(warningThresholdValue | default)]
[criticalThreshold=(criticalThresholdValue | default)]
[criticalPriority=(highest | high | medium |low |lowest)]
[degradedPriority=(highest |high |medium |low |lowest)]
[backgroundPriority=(highest | high | medium |low |lowest)]
[userLabel=pass:quotes[_diskPoolName_]]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
《DiskPool》
 a| 
您要為其設定屬性的磁碟集區名稱。將磁碟集區名稱括在方括弧中（[]）。如果磁碟集區名稱包含特殊字元或僅包含數字、則必須在方括弧內以雙引號（""）括住磁碟集區名稱。



 a| 
《DiskPools》
 a| 
您想要設定屬性的數個磁碟集區名稱。使用下列規則輸入磁碟集區的名稱：

* 將所有名稱括在方括弧中（[]）。
* 以空格分隔每個名稱。


如果磁碟集區名稱有特殊字元或數字、請使用下列規則輸入名稱：

* 將所有名稱括在方括弧中（[]）。
* 將每個名稱括在雙引號（""）內。
* 以空格分隔每個名稱。




 a| 
《allDiskPools》
 a| 
此參數可設定儲存陣列中所有磁碟集區的屬性。



 a| 
"REservedDriveCount"
 a| 
此參數會保留磁碟集區中每個磁碟機的空間、專門用於故障磁碟機的重建。此計數中的每個單位代表將一個故障磁碟機重新建構至其餘磁碟集區的容量。



 a| 
「warningThreshold」
 a| 
磁碟集區容量的百分比、您會在磁碟集區即將滿時收到警告警示。使用整數值。例如、值70表示70%。為達到最佳操作效果、此參數的值必須小於「criticalThreshold」參數的值。

有效值介於0到100之間。

預設值為50。

將此參數設為「0」會停用警告警示。

如果您將此值設為「預設」、則警告警示臨界值由控制器韌體決定。



 a| 
「嚴重臨界值」
 a| 
當磁碟集區即將滿時、您收到嚴重警示的磁碟集區容量百分比。使用整數值。例如、值70表示70%。為達到最佳作業效果、此參數的值必須大於「warningThreshold」參數的值。

有效值介於0到100之間。

預設值為85%。

將此參數設為「0」會停用警告警示和重大警示。

如果您將此值設為「預設」、則關鍵警示臨界值由控制器韌體決定。



 a| 
「重要優先」
 a| 
磁碟集區中重要事件的重建作業優先順序。例如、磁碟集區在至少兩個磁碟機故障後重建。

有效值包括「最高」、「高」、「中等」、「低」及「最低」。預設值為「最高」。



 a| 
「Dedgraded匯款」
 a| 
磁碟集區降級事件的重建作業優先順序。例如、磁碟集區在一個磁碟機故障後重建。

有效值包括「最高」、「高」、「中等」、「低」及「最低」。預設值為「高」。



 a| 
「背景優先順序」
 a| 
磁碟集區上的背景作業優先順序。

有效值包括「最高」、「高」、「中等」、「低」及「最低」。預設值為「低」。



 a| 
「userLabel」
 a| 
您要為磁碟集區指定的新名稱。將磁碟集區名稱括在雙引號（""）內。

|===


== 附註

每個磁碟集區名稱都必須是唯一的。您可以使用任何字母數字字元、底線（_）、連字號（-）和井號（#）的組合作為使用者標籤。使用者標籤最多可有30個字元。

您可以指定任意一組磁碟集區。如果您選取多個磁碟集區、設定「userLabel」的值會導致錯誤。

如果您未指定選用參數的值、則會指派預設值。



== 磁碟集區警示臨界值

每個磁碟集區都有兩個逐漸嚴重的警示層級、可在磁碟集區的儲存容量即將滿時通知使用者。警示的臨界值是磁碟集區中可用容量總計的已用容量百分比。警示包括：

* 警告：這是磁碟集區中已用容量即將滿的第一層警示。當達到警告警示的臨界值時、系統會產生「Needs Attention（需要注意）」條件、並將事件張貼至儲存管理軟體。嚴重臨界值會取代警告臨界值。預設的警告臨界值為50%。
* 嚴重-這是磁碟集區中已用容量即將滿的最嚴重警示等級。當達到關鍵警示的臨界值時、系統會產生「Needs Attention（需要注意）」條件、並將事件張貼至儲存管理軟體。嚴重臨界值會取代警告臨界值。嚴重警示的預設臨界值為85%。


若要生效、警告警示的值必須永遠小於嚴重警示的值。如果警告警示的值與嚴重警示的值相同、則只會傳送嚴重警示。



== 磁碟集區背景作業

磁碟集區支援下列背景作業：

* 重建
* 即時可用度格式（IAF）
* 格式
* 動態容量擴充（DCE-）
* 動態容量減量（簽帳卡讀卡機）
* 動態Volume Expansion（DVE）（對於磁碟資源池、DVE實際上不是背景作業、但DVE支援同步作業。）


磁碟集區不會將背景命令排入佇列。您可以依序啟動數個背景命令、但一次啟動多個背景作業會延遲完成先前啟動的命令。支援的背景作業的相對優先順序層級為：

. 重建
. 格式
. 廢時
. DCE/簽 帳卡讀卡機




== 最低韌體層級

7.83
