---
permalink: commands-a-z/set-snapgroup-enableschedule.html 
sidebar: sidebar 
keywords: set, snapshot, group, schedule 
summary: set snapGroup enableschedule命令可定義快照群組的快照映像拍攝排程。 
---
= 設定快照群組排程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「set snapGroup enableschedule」命令可定義快照群組的快照映像拍攝排程。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 語法

[source, cli, subs="+macros"]
----
set snapGroup pass:quotes[["_snapGroupName_"]]
enableSchedule=(TRUE | FALSE)
schedule (immediate | snapshotSchedule)
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
「napGroup」
 a| 
您要為其設定內容的快照群組名稱。將快照群組名稱括在方括弧（[]）內的雙引號（""）內。



 a| 
「enableSchedule」
 a| 
使用此參數可開啟或關閉排程快照作業的功能。若要開啟快照排程、請將此參數設為「true」。若要關閉快照排程、請將此參數設為「假」。

|===


== 附註

您可以使用字母數字字元、底線（_）、連字號（-）和井號（#）的任意組合來命名。名稱最多可包含30個字元。

「enableschedule」參數和「排程」參數可讓您排程建立快照群組的快照映像。使用這些參數、您可以排程每天、每週或每月快照（按日或依日期）。「enableschedule」參數會開啟或關閉排程快照的功能。啟用排程時、您可以使用「排程」參數來定義快照發生的時間。

此清單說明如何使用「排程」參數的選項：

* 「立即」-輸入命令後、即會建立快照映像、並開始寫入時複製作業。
* 「TartDate」（日期）-您要建立快照映像並執行寫入時複製作業的特定日期。輸入日期的格式為「M:DD:YY」。如果您未提供開始日期、則會使用目前日期。此選項的範例為「最新日期=06:27:11」。
* 「排定日期」：一週中您想要建立快照映像並執行寫入時複製作業的一天。您可以輸入以下值：「星期一」、「星期二」、「星期三」、「星期四」、「星期五」、 「星期六」、「星期一」及「全部」。此選項的範例為「排定日=星期三」。
* 「tartTime」（時間）：一天中您想要建立快照映像並開始執行寫入時複製作業的時間。輸入時間的格式為「hh：mm」、其中「hh」為小時、「mM」為小時後的分鐘數。使用24小時時鐘。例如下午2：00為14：00。此選項的範例為「* startTimes=14：27*」。
* 「排程時間間隔」是一段時間、以分鐘為單位、您希望在寫入時複製作業之間至少有一段時間。您可以建立排程、因為複製作業持續時間、所以在其中會有重疊的寫入時複製作業。您可以使用此選項、確保您有時間進行寫入時複製作業。「排程時間間隔」選項的最大值為1440分鐘。此選項的範例為「* scheduleInterval=180*」。
* 「結束日期」-您想要停止建立快照映像並結束寫入時複製作業的特定日期。輸入日期的格式為「M:DD:YY」。此選項的範例為「*結束日期= 11：26：11 *」。
* 「noEndDate」-如果您不想結束排程的寫入時複製作業、請使用此選項如果您稍後決定結束寫入時複製作業、則必須重新輸入「show snapGroup」命令、並指定結束日期。
* 「時程PerDay」-您希望排程在一天內執行的次數。此選項的範例為「timesPerDay = 4」。
* 「timezone」（時區）-使用此參數來定義儲存陣列運作的時區。您可以使用下列兩種方式之一來定義時區：
+
** "GMT"、"HH:mm"-時區與GMT"的偏移量。以小時和分鐘為單位輸入偏移量。例如、GMT-06：00是美國的中央時區。
** 「文字字串」-標準時區文字字串。例如：「美洲/芝加哥」或「澳洲/布里斯本」。時區文字字串區分大小寫。如果輸入不正確的文字字串、則會使用GMTTime。將文字字串括在雙引號中。




用於定義排程的程式碼字串類似下列範例：

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
如果您也使用「排程時間間隔」選項、韌體可在「時段間隔」選項和「排程時間間隔」選項之間選擇、方法是選取兩個選項的最低值。韌體會將1440除以您設定的「排定時間間隔」選項值、計算「排定時間間隔」選項的整數值。例如、1440/180 = 8。然後、韌體會將「timesPerDay」整數值與計算出的「排程間隔」整數值進行比較、並使用較小的值。

若要移除排程、請使用「刪除Volume」命令搭配「排程」參數。帶有「chschedule」參數的「刪除Volume」命令只會刪除排程、而不會刪除快照磁碟區。



== 最低韌體層級

7.83

7.86新增「排定日期」選項和「週期」選項。
