---
permalink: commands-a-z/set-snapvolume-converttoreadwrite.html 
sidebar: sidebar 
keywords: set, read-only, snapshot, volume, read/write, volume 
summary: set snapVolume convertToReadWrite命令會將唯讀磁碟區的快照磁碟區變更為讀取/寫入磁碟區的快照磁碟區。 
---
= 將只讀快照卷設定為讀/寫卷 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「set snapVolume convertToReadWrite」命令可將唯讀磁碟區的快照磁碟區變更為讀取/寫入磁碟區的快照磁碟區。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

您也可以使用此命令來識別讀寫磁碟區的新儲存庫磁碟區、或是設定儲存庫磁碟區的完整限制警告層級。



== 語法

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapImageVolumeName_"]] convertToReadWrite
[(repositoryVolume="repos_xxxx" |
repositoryVolume=pass:quotes[(_volumeGroupName_)] [capacity=pass:quotes[_capacityValue_]])
repositoryVolume=pass:quotes[(_diskPoolName_)] [capacity=pass:quotes[_capacityValue_]]]
[repositoryFullLimit=pass:quotes[_percentValue_]]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
「napVolume」
 a| 
您要從唯讀變更為讀/寫的快照磁碟區名稱。將快照磁碟區識別碼括在方括弧（[]）內的雙引號（""）內。



 a| 
「repositoryVolume」
 a| 
要用於讀寫磁碟區的儲存庫磁碟區名稱。

您有兩個選項可以定義儲存庫Volume的名稱：

* 使用現有的儲存庫Volume：名稱
* 執行此命令時、請建立新的儲存庫Volume


現有儲存庫磁碟區的名稱由兩部分組成：

* 「錯誤」一詞
* 儲存管理軟體指派給儲存庫Volume名稱的四位數數字識別碼


將現有儲存庫磁碟區的名稱以雙引號（""）括住。

若要在執行此命令時建立新的儲存庫磁碟區、您必須輸入要儲存庫磁碟區的磁碟區群組或磁碟集區名稱。或者、您也可以定義儲存庫Volume的容量。如果您想要定義容量、可以使用下列值：

* 整數值、代表基本Volume容量的百分比
* 表示基本Volume容量百分比的小數位值
* 儲存庫磁碟區的特定大小。大小的定義單位為「位元組」、「KB」、「MB」、「GB」或「TB」。


如果您不使用容量選項、儲存管理軟體會將容量設定為基礎Volume容量的20%。

當您執行此命令時、儲存管理軟體會為快照Volume建立儲存庫磁碟區。



 a| 
「repositoryFullLimit」
 a| 
儲存庫磁碟區容量的百分比、您會在其中收到快照映像儲存庫磁碟區即將滿的警告。使用整數值。例如、值70表示70%。預設值為75。

|===


== 附註

您可以使用任何字母數字字元、底線（_）、連字號（-）和井號（#）的組合作為使用者標籤。使用者標籤最多可有30個字元。

建立新的快照群組時、儲存管理軟體和韌體會自動建立儲存庫磁碟區名稱。您無法重新命名儲存庫磁碟區、因為重新命名儲存庫磁碟區會中斷與快照映像的連結。

Snapshot群組儲存庫Volume是可擴充的Volume、其結構是最多16個標準Volume實體的串聯集合。一開始、可擴充的儲存庫磁碟區只有一個元素。可擴充儲存庫磁碟區的容量與單一元素的容量完全相同。您可以附加額外的標準磁碟區、以增加可擴充儲存庫磁碟區的容量。然後、複合式可擴充儲存庫的Volume容量會成為所有串聯標準磁碟區容量的總和。

快照群組儲存庫磁碟區必須滿足下列總和的最低容量需求：

* 32 MB、可支援快照群組和寫入時複製處理的固定負荷。
* 復原處理的容量、是基礎Volume容量的1/5000。


控制器韌體和儲存管理軟體會強制執行最小容量。



== 最低韌體層級

7.83
