---
permalink: commands-a-z/set-volumes.html 
sidebar: sidebar 
keywords: set, volume, attributes, disk pool 
summary: set volume命令可定義磁碟集區中磁碟區的內容。 
---
= 設定磁碟池中磁碟區的磁碟區屬性 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「設置磁碟區」命令可定義磁碟集區中磁碟區的內容。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

[NOTE]
====
在磁碟集區包含超過32個磁碟區的組態中、此作業可能會導致主機I/O錯誤或內部控制器重新開機、因為在作業完成之前的逾時期間已到期。如果發生主機I/O錯誤或內部控制器重新開機、請將主機設為靜止狀態、然後再試一次作業。

====


== 語法

[source, cli, subs="+macros"]
----
set (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]] | volume <"wwID">)
pass:quotes[addCapacity = _capacityValue_][KB|MB|GB|TB|Bytes] |
pass:quotes[cacheFlushModifier=_cacheFlushModifierValue_] |
cacheReadPrefetch = (TRUE | FALSE) |
cacheWithoutBatteryEnabled=(TRUE | FALSE) |
mediaScanEnabled=(TRUE | FALSE) |
mirrorCacheEnabled=(TRUE | FALSE) |
preReadRedundancyCheck = (TRUE | FALSE) |
readCacheEnabled=(TRUE | FALSE) |
redundancyCheckEnabled = (TRUE | FALSE) |
pass:quotes[segmentSize = _segmentSizeValue_]
pass:quotes[userLabel = _userlabelValue_]
writeCacheEnabled=(TRUE | FALSE) |
dataAssuranceDisabled=(TRUE | FALSE)
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
《allVolumes》
 a| 
此參數可設定儲存陣列中所有磁碟區的內容。



 a| 
《Volume》（Volume）
 a| 
要定義其內容的Volume名稱。將磁碟區名稱括在方括弧（[]）內。如果Volume名稱含有特殊字元或數字、則必須在方括弧內以雙引號（""）括住Volume名稱。



 a| 
《Volume》（Volume）
 a| 
您要定義內容之磁碟區的全球識別碼（WWID）。將WWID以雙引號（""）括在角括弧（<>）內。

[NOTE]
====
執行此命令時、請勿在WWID中使用分號分隔符號。

====


 a| 
《Volume》（Volume）
 a| 
您要定義內容的數個Volume名稱。所有磁碟區都具有相同的內容。使用下列規則輸入磁碟區名稱：

* 將所有名稱括在方括弧中（[]）。
* 以空格分隔每個名稱。


如果磁碟區名稱有特殊字元或數字、請使用下列規則輸入名稱：

* 將所有名稱括在方括弧中（[]）。
* 將每個名稱括在雙引號（""）內。
* 以空格分隔每個名稱。




 a| 
《addCapacity》
 a| 
用於增加定義內容之磁碟區的儲存大小（容量）的設定。大小的定義單位為「位元組」、「KB」、「MB」、「GB」或「TB」。預設值為「位元組」。

此參數對精簡磁碟區無效。



 a| 
「cacheFlushModifier」
 a| 
磁碟區資料在資料排清到實體儲存設備之前、保留在快取中的最長時間。有效值列於「附註」區段。



 a| 
「cacheReadPrefetch」
 a| 
開啟或關閉快取讀取預先擷取的設定。若要關閉快取讀取預先擷取、請將此參數設為「假」。若要開啟快取讀取預先擷取、請將此參數設為「true」。



 a| 
「cacheWithoutBatteryEnabled'」
 a| 
此設定可在不使用電池的情況下開啟或關閉快取。若要在不使用電池的情況下開啟快取、請將此參數設為「true」。若要在不使用電池的情況下關閉快取、請將此參數設為「假」。



 a| 
「已啟用的媒體掃描」
 a| 
用於開啟或關閉Volume的媒體掃描的設定。若要開啟媒體掃描、請將此參數設為「true」。若要關閉媒體掃描、請將此參數設為「假」。（如果在儲存陣列層級停用媒體掃描、此參數將不會生效。）



 a| 
「已啟用鏡像快取」
 a| 
開啟或關閉鏡射快取的設定。若要開啟鏡射快取、請將此參數設為「true」。若要關閉鏡射快取、請將此參數設為「假」。



 a| 
"老闆"
 a| 
擁有該磁碟區的控制器。有效的控制器識別碼為「a」或「b」、其中「a」是插槽A中的控制器、而「b」是插槽B中的控制器僅當您想要變更Volume擁有者時、才使用此參數。



 a| 
「preReadRedundancyCheck」
 a| 
開啟或關閉讀取前備援檢查的設定。開啟讀取前備援檢查、可驗證包含讀取資料之等量磁碟區的RAID備援資料是否一致。讀取前備援檢查只會在讀取作業上執行。若要開啟預先讀取備援檢查、請將此參數設為「true」。若要關閉預先讀取備援檢查、請將此參數設為「假」。

[NOTE]
====
請勿在非備援磁碟區（例如RAID 0磁碟區）上使用此參數。

====


 a| 
「已啟用快取」
 a| 
開啟或關閉讀取快取的設定。若要開啟讀取快取、請將此參數設為「true」。若要關閉讀取快取、請將此參數設為「假」。



 a| 
「已啟用重複檢查」
 a| 
在媒體掃描期間開啟或關閉備援檢查的設定。若要開啟備援檢查、請將此參數設為「true」。若要關閉備援檢查、請將此參數設為「假」。



 a| 
「userLabel」
 a| 
您要為現有磁碟區指定的新名稱。請以雙引號（""）括住新的Volume名稱。



 a| 
「已啟用寫入快取」
 a| 
開啟寫入快取功能的設定。

|===


== 附註

使用此命令時、您可以指定一或多個選用參數。

您一次只能將這些參數套用至一個Volume：

* 《addCapacity》
* '大小'
* 「userLabel」




== 新增容量和區段大小

設定「addCapacity」參數或「Size」參數會啟動一項無法停止的長時間執行作業。這些長期執行的作業會在背景執行、不會妨礙您執行其他命令。若要顯示長期執行作業的進度、請使用「show volume actionProgress」命令。



== 快取排清修改器

此表列出快取齊面修正值的有效值。

[cols="2*"]
|===
| 價值 | 說明 


 a| 
《立即》
 a| 
資料一旦放入快取、就會立即排清。



 a| 
".25"
 a| 
資料會在250毫秒後排清。



 a| 
".5"
 a| 
資料會在500毫秒後排清。



 a| 
".75"
 a| 
資料會在750毫秒後排清。



 a| 
第1名
 a| 
資料會在1秒後排清



 a| 
"1.5"
 a| 
資料會在1500毫秒後排清。



 a| 
2）
 a| 
資料會在2秒後排清



 a| 
《5》
 a| 
資料會在5秒後排清



 a| 
《10》
 a| 
資料會在10秒後排清



 a| 
20歲
 a| 
資料會在20秒後排清



 a| 
《60》
 a| 
資料會在60秒（1分鐘）後排清。



 a| 
"120"
 a| 
資料會在120秒（2分鐘）後排清。



 a| 
《300》
 a| 
資料會在300秒（5分鐘）後排清。



 a| 
"1200"
 a| 
資料會在1200秒（20分鐘）後排清。



 a| 
"3600"
 a| 
資料會在3、600秒（1小時）後排清。



 a| 
《無限大》
 a| 
快取中的資料不受任何年齡或時間限制的限制。資料會根據控制器管理的其他準則進行排清。

|===


== 未啟用電池的快取

不含電池的寫入快取可在控制器電池完全耗盡、未充滿電或不存在時、繼續寫入快取。如果您將此參數設為「true」、但沒有不斷電系統（UPS）或其他備份電源、則儲存陣列的電力可能會中斷。如果停用寫入快取、此參數將不會生效。



== 修改優先順序

修改優先順序定義修改Volume內容時所使用的系統資源量。如果您選取最高優先順序層級、則磁碟區修改會使用最多的系統資源、進而降低主機資料傳輸的效能。



== 快取讀取預先擷取

「cacheReadPrefetch」參數可讓控制器將其他資料區塊複製到快取中、同時控制器讀取並複製主機從磁碟機要求的資料區塊到快取中。此動作可增加日後從快取執行資料要求的機會。對於使用循序資料傳輸的多媒體應用程式而言、快取讀取預先擷取非常重要。您使用的儲存陣列組態設定、會決定控制器讀取到快取的其他資料區塊數目。「cacheReadPrefetch」參數的有效值為「true」或「假」。



== 區段大小

區段大小決定控制器在磁碟區中的單一磁碟機上寫入多少資料區塊、然後再將資料寫入下一個磁碟機。每個資料區塊儲存512個位元組的資料。資料區塊是最小的儲存單位。區段的大小決定其包含多少資料區塊。例如、8-KB區段可容納16個資料區塊。64 KB區段可容納128個資料區塊。

當您輸入區段大小的值時、會對照控制器在執行時間提供的支援值來檢查該值。如果您輸入的值無效、控制器會傳回有效值清單。使用單一磁碟機進行單一要求時、其他磁碟機仍可同時處理其他要求。

如果磁碟區位於單一使用者正在傳輸大量資料（例如多媒體）的環境中、則當單一資料傳輸要求以單一資料等量磁碟區來處理時、效能就會達到最大化。（資料等量磁碟區是區段大小乘以磁碟區群組中用於資料傳輸的磁碟機數量。） 在此情況下、多個磁碟機用於相同的要求、但每個磁碟機只能存取一次。

若要在多使用者資料庫或檔案系統儲存環境中達到最佳效能、請設定區段大小、將滿足資料傳輸要求所需的磁碟機數量降至最低。



== 最低韌體層級

7.83
