---
permalink: commands-a-z/set-volumegroup.html 
sidebar: sidebar 
keywords: set, volume, group 
summary: set volumeGroup命令可定義Volume群組的內容。 
---
= 設定卷組 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「show volumeGroup」命令可定義Volume群組的內容。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

[NOTE]
====
每個命令只能執行一項作業（新增磁碟機、變更RAID層級或變更磁碟區群組擁有權）。您無法使用單一命令執行多項作業。

====


== 語法

[source, cli, subs="+macros"]
----
set volumeGroup pass:quotes[[_volumeGroupName_]]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]) ]|
[raidLevel=(0 | 1 | 3 | 5 | 6) ]|
[owner=(a|b)]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
「Volume Group」
 a| 
您要為其設定內容的Volume群組名稱。將Volume群組名稱括在方括弧中（[]）。



 a| 
《附加磁碟機》
 a| 
要新增至磁碟區群組的磁碟機位置。對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800和E5700控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。



 a| 
《raidLevel》
 a| 
Volume群組的RAID層級。有效值包括「0」、「1」、「3」、「5」或「6」。



 a| 
"老闆"
 a| 
擁有Volume群組的控制器。有效的控制器識別碼為「a」或「b」、其中「a」是插槽A中的控制器、而「b」是插槽B中的控制器僅當您想要變更Volume群組擁有者時、才使用此參數。

|===


== 附註

主機I/O錯誤可能會導致磁碟區群組超過32個磁碟區。此作業也可能導致內部控制器重新開機、因為逾時期間會在設定磁碟區群組定義之前結束。如果遇到此問題、請停止主機I/O作業、然後再試一次命令。

使用此命令時、您只能指定其中一個參數。

[NOTE]
====
指定「addDrives」參數或「raidLevel」參數會啟動一項無法停止的長時間執行作業。

====
「addDrives」參數同時支援大容量磁碟機匣和低容量磁碟機匣。大容量磁碟機匣具有可容納磁碟機的抽屜。從磁碟機匣中滑出抽取器、以便存取磁碟機。低容量磁碟機匣沒有抽屜。對於大容量磁碟機匣、您必須指定磁碟機匣的識別碼（ID）、匣的識別碼、以及磁碟機所在插槽的識別碼。對於低容量磁碟機匣、您只需要指定磁碟機匣的ID、以及磁碟機所在插槽的ID。對於低容量磁碟機匣、識別磁碟機位置的另一種方法是指定磁碟機匣的ID、將抽取匣的ID設為「0」、然後指定磁碟機所在插槽的ID。



== 疑難排解

嘗試透過新增磁碟機（也稱為動態容量擴充（DCE-Dynamic Capacity Expansion、簡稱DCE-Dce）來擴充大容量群組、可能會失敗、並顯示下列訊息：

「傳回代碼：錯誤26：由於磁碟區群組中的磁碟機數量和相關磁碟區的區段大小、因此無法完成修改作業。使用變更區段大小選項、將Volume群組中所有磁碟區的區段大小減至128 KB或以下。然後重試該作業

執行7.35.xx.xx韌體的系統可能會失敗、並顯示下列訊息、而非上述訊息：

「傳回代碼：錯誤462 -無法執行符號程序、因為韌體無法配置足夠的快取記憶體。發生錯誤時的作業：proc_startVolum

除了上述訊息之外、也可能發生重大事件記錄（MEL）事件、指出可用的快取不足、無法完成DCE作業。

任何執行7.xx韌體的控制器都可能會遇到此問題。

由於需要足夠的記憶體來緩衝從原始磁碟區讀取的資料、並將資料寫入擴充磁碟區。擴充作業中的磁碟機數量、等量磁碟區大小、以及是否啟用鏡射作業等組合、可能會導致可用的記憶體不足、無法完成DCE作業。

如果遇到上述情況、可能的因應措施如下：

* 使用其他未指派的磁碟機建立所需大小的Volume群組。
* 刪除目前的Volume群組、然後以所需的磁碟機數量重新建立Volume群組。
* 請減少所使用的區段大小、然後重試此作業。
* 如果可能、請將額外的記憶體新增至控制器、然後重試此作業。




== 最低韌體層級

7.10新增RAID 6功能。

7.30移除「可用度」參數。

7.60新增「drawerID」使用者輸入。
