---
permalink: commands-a-z/set-storagearray-isnsregistration.html 
sidebar: sidebar 
keywords: set, storage, array, isns, registration 
summary: set storageArray isnslRegistration命令可讓您在IPv4或IPv6網際網路儲存名稱服務（SNSSNS>）伺服器上列出儲存陣列。 
---
= 設定儲存陣列iSNS登錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「show storageArray isnRegistration」命令可讓您在IPv4或IPv6網際網路儲存名稱服務（SNSSNS>）伺服器上列出儲存陣列。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 適用於IPV4的語法

[source, cli, subs="+macros"]
----
set storageArray isnsRegistration=(TRUE | FALSE)
isnsIPv4ConfigurationMethod=[static | dhcp]
isnsIPv4Address=pass:quotes[_ipAddress_]
[isnsListeningPort]
----


== IPv6的語法

[source, cli, subs="+macros"]
----
set storageArray isnsRegistration=(TRUE | FALSE)
isnsIPv6Address=pass:quotes[_ipAddress_]
[isnsListeningPort]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
《isnstRegistration》
 a| 
在iSNS伺服器上登錄iSCSI目標的方法。將參數設為「true」以列出iSCSI目標。

當您將此參數設為「true」時、您也必須將這些參數用於IPv4組態：

* 「isnsIPV4Configuration方法」
* 「isnsIPV4Address」


當您將此參數設為「true」時、您也必須將這些參數用於IPv6組態：

* 「isnsIPV6Address」


或者、您也可以使用「isnslisteningPort」參數來定義連接埠監控器、並管理伺服器的流量。

若要從iSNS伺服器移除儲存陣列的登錄、請將此參數設為「假」。



 a| 
「isnslIPv6組態方法」
 a| 
您要用來定義iSNS伺服器組態的方法。您可以選取「靜態」來輸入IPv4 iSNS伺服器的IP位址。對於IPV4、您可以輸入「dhcps」、選擇讓動態主機組態傳輸協定（DHCP）伺服器選取iSNS伺服器IP位址。若要啟用DHCP、您必須將「isnsIPV4Address」參數設定為「0.00.0」。



 a| 
「isnsIPV4Address」
 a| 
用於連線至iSNS伺服器的IPV4位址。使用此參數搭配「最短」值以進行IPv4組態。如果您選擇讓DHCP伺服器設定IPV4網際網路isSNs伺服器的IP位址、則必須將「isnsIPV4Address」參數設定為「0.00.0」。



 a| 
「isnsIPv6位址」
 a| 
用於連線至iSNS伺服器的IPv6位址。



 a| 
「isnslisteningPort」
 a| 
要用於iSNS伺服器接聽連接埠的連接埠號碼。偵聽連接埠的值範圍為「49152」到「65535"。預設值為「3205」。

偵聽連接埠位於伺服器上、並執行下列活動：

* 監控傳入的用戶端連線要求
* 管理伺服器的流量


當用戶端要求與伺服器進行網路工作階段時、接聽程式會收到實際的要求。如果用戶端資訊與接聽程式資訊相符、則接聽程式會授與資料庫伺服器的連線。

|===


== 附註

透過iSNS傳輸協定、可在TCP/IP網路上自動探索、管理及設定iSCSI裝置和光纖通道裝置。與Fibre Channel網路中的儲存探索和管理服務相若的是、而這些服務可讓市售IP網路以與儲存區域網路類似的容量運作。此外、由於其能夠模擬Fibre Channel Fabric服務、並同時管理iSCSI裝置和Fibre Channel裝置、因此也能順暢整合IP網路和Fibre Channel網路。

DHCP伺服器會將網路位址等組態參數傳遞給IP節點。DHCP可讓用戶端取得其運作所需的所有IP組態參數。DHCP可讓您自動分配可重複使用的網路位址。



== 最低韌體層級

7.10.
