---
permalink: commands-a-z/set-tray-serviceallowedindicator.html 
sidebar: sidebar 
keywords: set, tray, service, action, allowed, indicator 
summary: Set tray serviceAllowedindicator命令會開啟或關閉電源風扇容器、互連電池容器或環境服務模組（ESM）容器上的「允許維修操作」指示燈。 
---
= 設定允許的紙匣服務動作指示
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「set tray serviceAllowedindicator」命令會開啟或關閉電源風扇容器、互連電池容器或環境服務模組（ESM）容器上的「服務行動允許」指示燈。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800、E5700、 EF600和EF300陣列、只要安裝所有SMcli套件即可。



== 角色

若要在E2800、E5700、EF600或EF300儲存陣列上執行此命令、您必須具有「儲存管理員」或「支援管理員」角色。



== 背景

如果儲存陣列不支援「允許服務動作」指示燈功能、此命令會傳回錯誤。如果儲存陣列支援該命令、但無法開啟或關閉指示燈、則此命令會傳回錯誤訊息。

若要開啟或關閉控制器機箱上的「允許維修操作」指示燈、請使用「設置控制器服務支援指標」命令。



== 語法

[listing, subs="+macros"]
----
set tray pass:quotes[[_trayID_]]
(powerFan [(left | right | top | bottom)] |
interconnect |
esm [(left | right | top | bottom)]) |
battery [(left | right)] |
fanCanister [(left | right)]  |
powerCanister [(top | bottom)] |
serviceAllowedIndicator=(on | off)
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
"紙匣"
 a| 
電源風扇容器、互連容器、esm容器或電池箱所在的匣。紙匣ID值為0至99。將紙匣ID值括在方括弧（[]）內。如果您未輸入紙匣ID值、控制器紙匣的紙匣ID為預設值。



 a| 
《強力粉絲》
 a| 
您想要開啟或關閉的電源風扇容器上的「服務行動允許」指示燈。有效的電源風扇機箱識別碼為「左」、「右」、「上」或「下」。請將電力風扇容器識別碼括在方括弧（[]）內。



 a| 
互連
 a| 
互連電池箱的「維修操作」允許指示燈亮起。



 a| 
"ESM-"
 a| 
服務動作可讓ESM儲存箱的指示燈亮起。有效的esm儲存容器識別碼為「左」、「右」、「上」或「下」。



 a| 
電池
 a| 
電池的「允許維修操作」指示燈。有效的電池識別碼為「左」或「右」。



 a| 
「FanCanister」
 a| 
風扇容器的維修操作允許指示燈亮起。有效的風扇容器識別碼為「左」或「右」。



 a| 
《權力之人》
 a| 
電力容器的維修操作允許指示燈亮起。有效的電力容器識別碼為「TOP」或「Bottom」。



 a| 
「服務指標」
 a| 
用於開啟或關閉「允許服務動作」指示燈的設定。若要開啟「允許維修操作」指示燈、請將此參數設為「開啟」。若要關閉「允許維修操作」指示燈、請將此參數設為「關閉」。

|===


== 附註

此命令最初定義為搭配CE6998控制器匣使用在推出CE6998控制器匣之前、隨附的控制器匣不支援此命令



== 範例

此命令用於打開紙盤5中左側ESM的服務操作允許指示燈（IP地址155.155.155.155）。

[listing]
----
SMcli 123.145.167.214 123.145.167.215 -c "set tray [5]
ESM [left] serviceAllowedIndicator=on;"
----


== 最低韌體層級

6.14新增下列參數：

* 《強力粉絲》
* 互連


6.16新增下列參數：

* "紙匣"
* "ESM-"


7.60新增識別碼「TOP」和「Bottom」。

7.60新增了「PowerCanister」和「FanCanister」參數。
