---
permalink: commands-a-z/show-alldrives.html 
sidebar: sidebar 
keywords: show, drive 
summary: show allDrives命令會傳回儲存陣列中磁碟機的相關資訊。 
---
= 顯示磁碟機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「show allDrives」命令會傳回儲存陣列中磁碟機的相關資訊。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

對於儲存陣列中的每個磁碟機、此命令會傳回下列資訊：

* 磁碟機總數
* 磁碟機類型（SAS或NVMe4K）
* 基本磁碟機的相關資訊：
+
** 紙匣位置和插槽位置
** 狀態
** 容量
** 資料傳輸率
** 產品ID
** 韌體層級


* SSD 磁碟機的使用壽命相關資訊（如果陣列不包含 SSD 磁碟機，則不會顯示此資訊）：
+
** 平均清除數。
** 剩餘的備用區塊。
** 使用的耐受度百分比（11.41版本中的新功能）。「使用的持久度百分比」是指迄今寫入SSD磁碟機的資料量、除以磁碟機的理論寫入總限制。


* 磁碟機通道的相關資訊：
+
** 紙匣位置和插槽位置
** 偏好的通道
** 備援通道


* 熱備援涵蓋範圍
* 每個磁碟機的詳細資料
+
[NOTE]
====
NVMe磁碟機無法取得製造日期資訊。

====




== 語法

[source, cli, subs="+macros"]
----
show ((allDrives
[driveMediaType=(HDD | SSD | unknown | allMedia)] |
[driveType=( SAS | NVMe4K)]) |
(drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]]))
summary
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
"allDrives"
 a| 
此設定可傳回儲存陣列中所有磁碟機的相關資訊。



 a| 
「DiveMediaType」
 a| 
您要擷取資訊的磁碟機媒體類型。下列值為有效的磁碟機媒體類型：

* "HDD"（HDD）-如果磁碟機匣中有硬碟機、請使用此選項
* 「SD」-如果磁碟機匣中有固態磁碟機、請使用此選項
* "unknown"（未知）-如果您不確定磁碟機匣中有哪些類型的磁碟機媒體、請使用此選項
* "ALLMEDIA"（ALLMEDIA）-如果您想要使用磁碟機匣中的所有磁碟機媒體類型、請使用此選項




 a| 
「DiveType」
 a| 
您要擷取資訊的磁碟機類型。您無法混用磁碟機類型。

有效的磁碟機類型包括：

* 「as」
* 《NVMe4K》


如果未指定磁碟機類型、則命令預設為任何類型。



 a| 
「Dive」或「Drives」
 a| 
對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800和E5700控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。



 a| 
《摘要》
 a| 
此設定可傳回指定磁碟機的狀態、容量、資料傳輸率、產品ID和韌體版本。

|===


== 附註

若要判斷儲存陣列中所有磁碟機的類型和位置資訊、請使用「allDrives」參數。

若要判斷儲存陣列中SAS磁碟機的相關資訊、請使用「driveType」參數。

若要判斷特定位置的磁碟機類型、請使用「驅動器」參數、然後輸入磁碟機的匣ID和插槽ID。

"driv"參數同時支援大容量磁碟機匣和低容量磁碟機匣。大容量磁碟機匣具有可容納磁碟機的抽屜。從磁碟機匣中滑出抽取器、以便存取磁碟機。低容量磁碟機匣沒有抽屜。對於大容量磁碟機匣、您必須指定磁碟機匣的識別碼（ID）、匣的識別碼、以及磁碟機所在插槽的識別碼。對於低容量磁碟機匣、您只需要指定磁碟機匣的ID、以及磁碟機所在插槽的ID。對於低容量磁碟機匣、識別磁碟機位置的另一種方法是指定磁碟機匣的ID、將抽取匣的ID設為「0」、然後指定磁碟機所在插槽的ID。



== 最低韌體層級

5.43

7.60新增「drawerID」使用者輸入和「driveMediaType」參數。

8.41針對E2800、E5700或EF570系統中的SSD磁碟機、新增耗用壽命報告資訊、其形式為使用的持久度百分比。
