---
permalink: commands-a-z/show-cgsnapimage.html 
sidebar: sidebar 
keywords: show, consistency, group, snapshot, image 
summary: show CGSnapImage命令會顯示一個或多個快照一致性群組中的快照映像或多個快照映像。 
---
= 顯示一致性群組快照映像
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「show CGSnapImage」命令會顯示一個或多個快照一致性群組中的快照映像或多個快照映像。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800、E5700、 EF600和EF300陣列、只要安裝所有SMcli套件即可。



== 角色

若要在E2800、E5700、EF600或EF300儲存陣列上執行此命令、您必須具有儲存管理員角色。



== 語法

[listing, subs="+macros"]
----
show ((CGSnapImage pass:quotes[[(_CGSnapImageName_ | _CGSnapImageSequenceNumber_)]]) |
(CGSnapImages pass:quotes[[(_CGSnapImageNumber1_ ... _CGSnapImageNumbern_ |
_CGSnapImageSequenceNumber1_ ... _CGSnapImageSequenceNumbern_)]]) |
allCGSnapImages
[summary]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
「CGSnapImage」或「CGSnapImages」
 a| 
一致性群組中的快照映像名稱。快照映像的名稱由兩部分組成：

* 一致性群組的名稱
* 一致性群組中快照映像的識別碼。


快照映像的識別碼可以是下列其中一項：

* 整數值、是一致性群組中快照的順序編號。
* 「最新」-如果您想要顯示在一致性群組中建立的最新快照映像、請使用此選項。
* "OLDEST"（最舊）-如果您想要顯示在一致性群組中建立的最早快照映像、請使用此選項。


將快照映像名稱以雙引號（""）括在方括弧（[]）內。

您可以輸入多個快照映像名稱或序號。將所有快照映像名稱括在一組雙引號（""）內方括弧（[]）內。以空格分隔每個快照映像名稱。



 a| 
《allCGSnapImages》
 a| 
此設定可從一致性群組傳回所有快照映像。



 a| 
《摘要》
 a| 
此設定可傳回儲存陣列中所有快照映像的簡短資訊清單。

|===


== 附註

快照映像的名稱有兩個部分以分號分隔（：）：

* 快照一致性群組的識別碼
* 快照映像的識別碼


例如、如果您想要在名稱為snapCGroup1的Snapshot一致性群組中顯示Snapshot映像12345、請使用下列命令：

[listing]
----
show CGsnapImage ["snapCGroup1:12345"];
----
若要在名稱為snapCGroup1的快照一致性群組中顯示最新的快照映像、請使用下列命令：

[listing]
----
show CGsnapImage ["snapCGroup1:newest"];
----
若要在多個名稱為snapCGroup1、snapCGroup2和snapCGroup3的快照一致性群組中顯示快照映像、請使用下列命令：

[listing]
----
show CGsnapImages ["snapCGroup1:12345 snapCGroup2:newest snapCGroup3:oldest"];
----
請注意、在這些範例中、快照一致性群組名稱與快照映像識別碼之間會以分號（：）分隔。



== 最低韌體層級

7.83
