---
permalink: commands-a-z/show-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: show, ssd, cache, statistics 
summary: show ssdCache命令會顯示SSD快取使用量的相關資料。 
---
= 顯示SSD快取統計資料
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「show ssdCache」命令會顯示SSD快取使用量的相關資料。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括 E2700 、 E5600 、 E2800 、 E5700 、 EF600 和 EF300 陣列、只要安裝了所有 SMcli 套件即可。



== 角色

若要在 E2800 、 E5700 、 EF600 或 EF300 儲存陣列上執行此命令、您必須具有「支援管理員」角色。



== 語法

[listing, subs="+macros"]
----
show ssdCache pass:quotes[[_ssdCacheName_]] [ssdCacheStatistics]
[controller=(a|b|both)]
pass:quotes[[file="_filename_"]]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
SdCache
 a| 
您要擷取資訊的SSD快取名稱。將SSD快取名稱括在方括弧（[]）內。如果SSD快取名稱包含特殊字元或數字、您必須在方括弧內以雙引號（""）括住SSD快取名稱。



 a| 
「sdCacheStatistics」
 a| 
「show ssdCache」命令的選用參數、表示您要擷取快取統計資料。



 a| 
"控制器"
 a| 
每個控制器都會儲存其擁有的磁碟區的SSD快取中繼資料。因此、每個控制器都會維護和顯示SSD快取統計資料。有效的控制器識別碼為「A」、「b」或「兩者」、其中「A」是插槽A中的控制器、「b」是插槽B中的控制器、「兩者」都是控制器。將控制器識別碼括在方括弧（[]）內。如果您未指定控制器、預設值為「兩者」。



 a| 
檔案
 a| 
您要儲存SSD快取統計資料的檔案路徑和檔案名稱。當您將統計資料儲存至檔案時、可以使用其他統計資料。

將檔案名稱括在雙引號（""）內。例如：

「file="C:\Program Files\CLI/logs\ssdccachestscsv"」。

您可以使用任何檔案名稱、但必須使用「.csv"副檔名。

|===


== 附註

畫面上會顯示下列統計資料：

* *讀取*-啟用SSD快取的磁碟區的主機讀取總數。
+
比較讀取與寫入的關係。讀取必須大於寫入、才能有效執行SSD快取作業。讀取與寫入的比率越高、快取的操作就越好。

* *寫入*-主機寫入啟用SSD快取的磁碟區的總數。
* *快取命中次數*-快取命中次數的計數。
* *快取命中次數（%）*-衍生自快取命中次數/總讀取次數。
+
若要有效執行SSD快取作業、快取命中率應大於50%。少數人可能表示以下幾點：

+
** 讀取與寫入的比率太小。
** 不會重複讀取。
** 快取容量太小。
+
[NOTE]
====
若要協助判斷理想的SSD快取容量、您可以使用「Start ssdCache [ssdCacheName] performanceModeling」命令來執行效能建模工具。

====


* *快取分配（%）*：已分配的SSD快取儲存容量、以此控制器可用的SSD快取儲存空間百分比表示。衍生自已分配位元組/可用位元組。
+
快取分配百分比通常顯示為100%。如果這個數字低於100%、表示快取尚未暖機、或SSD快取容量大於所有正在存取的資料。在後一種情況下、較小的SSD快取容量可提供相同等級的效能。請注意、這並不表示快取資料已放入SSD快取、只是準備步驟、資料才可放入SSD快取。

* *快取使用率（%）*：包含已啟用磁碟區資料的SSD快取儲存容量、以已配置SSD快取儲存空間的百分比表示。此值代表SSD快取的使用率或密度。衍生自使用者資料位元組/已分配位元組。
+
快取使用率百分比通常低於100%、可能低得多。此數字顯示使用快取資料填滿SSD快取容量的百分比。此數字低於100%的原因是SSD快取的每個分配單元、即SSD快取快取區塊、都被分割成較小的單元、稱為子區塊、因此會稍微獨立地填滿。較高的數字通常較好、但效能增益可能很大、即使數量較少。



當您將資料儲存至檔案時、還會包含這些額外的統計資料：

* *讀取區塊*-主機讀取區塊數。
* *寫入區塊*-主機寫入區塊數。
* *完整命中率區塊*-區塊快取命中率。
+
完整的命中率區塊表示完全從SSD快取讀取的區塊數。SSD快取只有在快取命中次數滿的作業中、才有助於提升效能。

* *部分命中次數*：SSD快取中至少有一個區塊（但不是所有區塊）的主機讀取次數。這是SSD快取* Miss *、可從基礎磁碟區滿足讀取需求。
+
部分快取命中率和部分快取命中率區塊是因為在SSD快取中只有部分資料的作業所致。在此情況下、作業必須從快取的HDD Volume擷取資料。SSD快取對這類命中率沒有任何效能優勢。如果部分快取命中率區塊數高於完整快取命中率區塊、則不同的I/O特性類型（檔案系統、資料庫或Web伺服器）可能會改善效能。

* *部分點閱數-區塊*-部分點閱數。
+
部分快取命中率和部分快取命中率區塊是因為在SSD快取中只有部分資料的作業所致。在此情況下、作業必須從快取的HDD Volume擷取資料。SSD快取對這類命中率沒有任何效能優勢。如果部分快取命中率區塊數高於完整快取命中率區塊、則不同的I/O特性類型（檔案系統、資料庫或Web伺服器）可能會改善效能。

* *未命中*：SSD快取中沒有任何區塊的主機讀取數目。這是SSD快取記憶體遺漏、從基礎磁碟區讀取的內容都很滿意。
* *未命中數-區塊*-未命中區塊數。
* *移入動作（主機讀取）*-從基礎磁碟區複製資料到SSD快取的主機讀取次數。
* *填入動作（主機讀取）-區塊*-「讀取資料」動作（主機讀取）中的區塊數。
* *移入動作（主機寫入）*-從基礎磁碟區複製資料到SSD快取的主機寫入次數。
+
由於寫入I/O作業、未填滿快取組態設定的「讀取動作（主機寫入）」計數可能為零。

* *讀取動作（主機寫入）-區塊*-「讀取動作」（主機寫入）中的區塊數。
* *無效動作*-資料在SSD快取中失效/移除的次數。快取會針對每個主機寫入要求、強制單元存取（FUA）的每個主機讀取要求、每個驗證要求、以及其他情況執行無效作業。
* *資源回收動作*：SSD快取區塊重新用於其他基礎磁碟區和（或）不同LBA範圍的次數。
+
若要有效執行快取作業、可回收資源的數量必須少於讀寫作業的總數量。如果回收動作數量接近讀取和寫入的合併數量、則SSD快取會發生負載衝擊。快取容量需要增加、或工作負載不適合搭配SSD快取使用。

* *可用位元組*：SSD快取中可供此控制器使用的位元組數。
+
可用位元組、已分配位元組和使用者資料位元組、用於計算快取分配%和快取使用率%。

* *已分配位元組*-此控制器從SSD快取配置的位元組數。從SSD快取配置的位元組可能是空的、或可能包含來自基礎磁碟區的資料。
+
可用位元組、已分配位元組和使用者資料位元組、用於計算快取分配%和快取使用率%。

* *使用者資料位元組*：SSD快取中包含基礎磁碟區資料的已分配位元組數。
+
可用位元組、已分配位元組和使用者資料位元組、用於計算快取分配%和快取使用率%。





== 最低韌體層級

7.84

11.80 新增 EF600 和 EF300 陣列支援
