---
permalink: commands-a-z/start-snapimage-rollback.html 
sidebar: sidebar 
keywords: start, snapshot, image, rollback 
summary: 「Start SnapImage復原」命令會針對一組快照映像啟動復原作業。 
---
= 啟動快照映像回溯 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「Start SnapImage復原」命令會針對一組快照映像啟動復原作業。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有儲存管理員角色。



== 背景

基礎磁碟區的內容會立即變更、以符合所選快照映像磁碟區的時間點內容。成功完成復原作業後、基礎Volume便可立即用於讀取/寫入要求。若要停止快照映像復原作業、請使用「停止復原SnapImage」命令。

與快照映像相關聯的儲存庫磁碟區會繼續追蹤在復原作業完成後、基礎磁碟區與快照映像磁碟區之間所發生的任何新變更。

[NOTE]
====
您無法將此命令用於線上磁碟區複本所涉及的快照映像。

====


== 語法

[source, cli, subs="+macros"]
----
pass:quotes[start snapImage ["_snapImageName_"]] rollback
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
「napImage」
 a| 
快照映像的名稱。快照映像的名稱由兩部分組成：

* 快照群組的名稱
* 快照群組中快照映像的識別碼


快照映像的識別碼可以是下列其中一項：

* 整數值、即快照群組中快照的順序編號。
* 「最新」-如果您想要顯示快照群組中建立的最新快照映像、請使用此選項。
* "OLDEST"（最舊）-如果您想要顯示快照群組中建立的最早快照映像、請使用此選項。


將快照映像名稱以雙引號（""）括在方括弧（[]）內。

|===


== 附註

快照映像的名稱有兩個部分以分號分隔（：）：

* 快照群組的識別碼
* 快照映像的識別碼


例如、如果您想要在名稱為snapGroup1的快照群組中啟動Snapshot映像12345的復原作業、請使用下列命令：

[listing]
----
start snapImage ["snapGroup1:12345"] rollback;
----
若要針對快照群組中名稱為snapGroup1的最新快照映像啟動復原作業、請使用下列命令：

[listing]
----
start snapImage ["snapGroup1:newest"]rollback;
----


== 最低韌體層級

7.83
