---
permalink: commands-a-z/start-secureerase-drive.html 
sidebar: sidebar 
keywords: start, fde, secure, drive, erase 
summary: start secureErase磁碟機命令會清除一或多個完整磁碟加密（FDE）磁碟機中的所有資料、以便重新使用為FDE磁碟機。 
---
= 啟動 FDE 安全驅動器擦除 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「Start secureErase drives」命令會清除一或多個完整磁碟加密（FDE）磁碟機中的所有資料、以便重新使用為FDE磁碟機。



== 支援的陣列

此命令適用於任何個別儲存陣列，包括 E4000 ， E2700 ， E5600 ， E2800 ， E5700 ， EF600 和 EF300 陣列，只要安裝了所有 SMCLI 套件即可。



== 角色

若要在 E4000 ， E2800 ， E5700 ， EF600 或 EF300 儲存陣列上執行此命令，您必須具有安全管理角色。



== 背景

僅當FDE磁碟機不再是安全磁碟區群組或磁碟集區的一部分、或安全金鑰不明時、才執行此命令。

[NOTE]
====
若要在磁碟機鎖定時清除FIPS磁碟機、且無法使用安全金鑰來解除鎖定、請使用「設磁碟機安全性ID」命令。

====


== 語法

[source, cli, subs="+macros"]
----
[start secureErase (drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]])
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
「Dive」或「Drives」
 a| 
對於大容量磁碟機匣、請指定磁碟機的匣ID值、藥櫃ID值及插槽ID值。對於低容量磁碟機匣、請指定磁碟機的匣ID值和插槽ID值。紙匣ID值為0至99。藥櫃ID值為1至5。

所有插槽ID上限為24。插槽ID值的開頭為0或1、視紙匣機型而定。與E2800和E5700控制器相容的磁碟機匣具有從0開始的插槽ID編號。與E2700和E5600控制器相容的磁碟機匣具有插槽ID編號、從1開始。

將紙匣ID值、藥櫃ID值和插槽ID值括在方括弧（[]）中。

[NOTE]
====
磁碟機清單不能包含儲存陣列中的所有磁碟機、否則會拒絕該命令。若要確保清除所有磁碟機的安全、請執行此命令兩次、並在兩個不同的群組中指定磁碟機清單。

====
|===


== 附註

控制器韌體會建立一個鎖定、限制FDE磁碟機的存取。FDE磁碟機的狀態稱為「安全功能」。當您建立安全金鑰時、狀態會設為「啟用安全性」、這會限制存取儲存陣列內所有FDE磁碟機。



== 最低韌體層級

7.40
