---
permalink: commands-a-z/start-volume-initialize.html 
sidebar: sidebar 
keywords: initialize, thin volume 
summary: start volume initialize命令可初始化或重新初始化精簡磁碟區。 
---
= 初始化精簡磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「Start volume initialize」命令可初始化或重新初始化精簡磁碟區。



== 支援的陣列

此命令適用於任何個別儲存陣列、包括E2700、E5600、E2800、E5700、 EF600和EF300陣列、只要安裝所有SMcli套件即可。



== 角色

若要在E2800、E5700、EF600或EF300儲存陣列上執行此命令、您必須具有儲存管理員角色。



== 背景

此動作取決於使用的參數：

* 如果不使用任何選用參數、此命令會刪除精簡磁碟區上的資料。儲存庫Volume容量不受影響。
* 此命令可搭配任何選用參數使用、因此會導致重新初始化和儲存庫Volume動作。


[NOTE]
====
初始化精簡磁碟區會啟動一項無法停止的長時間執行作業。

====


== 語法

[listing, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
pass:quotes[[existingRepositoryLabel=_existingRepositoryName_]]
pass:quotes[[diskPool=_diskPoolName_ capacity=_capacityValue_]]
[retainRepositoryMembers=(TRUE|FALSE)]
----


== 參數

[cols="2*"]
|===
| 參數 | 說明 


 a| 
《Volume》（Volume）
 a| 
開始初始化的磁碟區名稱。將磁碟區名稱括在方括弧（[]）內。如果Volume名稱包含特殊字元或數字、則必須在方括弧內以雙引號（""）括住Volume名稱。



 a| 
「現有的儲存庫標籤」
 a| 
此參數會依指定的候選磁碟區取代儲存庫磁碟區。

* 指定的值是現有的儲存庫Volume使用者標籤。指定的磁碟區必須是未使用的儲存庫磁碟區、其名稱格式必須正確。
* 如果新指定的儲存庫磁碟區位於不同的磁碟集區、精簡磁碟區將變更該集區的擁有權。
* 預設會刪除舊儲存庫磁碟區。


如果現有儲存庫磁碟區名稱包含特殊字元或僅包含數字、則必須以雙引號（""）括住磁碟區名稱。



 a| 
《DiskPool》
 a| 
您要在其中建立具有指定容量的新儲存庫磁碟區的磁碟集區名稱。如果磁碟集區名稱包含特殊字元或僅包含數字、則必須以雙引號（""）括住磁碟集區名稱。

您必須使用此參數搭配「capcap處理 量」參數、才能建立具有指定容量的新儲存庫Volume。



 a| 
容量
 a| 
您要為所建立的儲存庫Volume設定的大小。大小的定義單位為「位元組」、「KB」、「MB」、「GB」或「TB」。

實體容量下限為4 GB。

實體容量上限為257TB。

您必須將此參數與「diskPool」參數搭配使用、才能建立具有指定容量的新儲存庫Volume。



 a| 
《reitrepositoryMemges》（《保存成員》）
 a| 
如果此參數設為「true」、則會保留舊儲存庫。預設會刪除舊儲存庫。如果重複使用現有儲存庫、則會忽略此參數。

|===


== 附註

如果您未使用「volume」參數指定Volume、此命令會重設儲存庫中的中繼資料、實際上會使精簡磁碟區在主機上顯示為空白。如果您使用「* Volume *」參數指定Volume、則該Volume會被新建立的Volume取代、或是由現有Volume取代、如果您使用「現有的儲存空間標籤」參數指定。如果您使用位於不同磁碟集區中的「現有儲存空間標籤」參數來指定現有磁碟區、則精簡磁碟區會將擁有權變更為新的磁碟集區。

精簡磁碟區的磁碟區參數（例如虛擬容量、配額和警告臨界值）會在重新初始化精簡磁碟區之後保留先前的值。

[NOTE]
====
立即可用度格式（IAF）不適用於大於64 TB的磁碟區。

====
下表列出精簡磁碟區的容量限制。

[cols="2*"]
|===
| 容量類型 | 尺寸 


 a| 
最小虛擬容量
 a| 
32 MB



 a| 
最大虛擬容量
 a| 
256 TB



 a| 
最小實體容量
 a| 
4 GB



 a| 
最大實體容量
 a| 
257TB

|===
精簡磁碟區支援標準磁碟區執行的所有作業、但有下列例外：

* 您無法變更精簡磁碟區的區段大小。
* 您無法啟用精簡磁碟區的預先讀取備援檢查。
* 您無法在Volume複本中使用精簡磁碟區做為目標磁碟區。
* 您無法在同步鏡射作業中使用精簡磁碟區。


如果您想要將精簡磁碟區變更為標準磁碟區、請使用Volume複製作業來建立精簡磁碟區的複本。Volume複本的目標永遠是標準Volume。



== 最低韌體層級

7.83

8.30可將精簡磁碟區的最大容量增加至256 TB。
